/**
 * Pi extension: `ast_grep` tool — structural search via the pi-rs ast-grep
 * subcommand.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/ast-grep-extension.ts and rebuild.
 *
 * Surface mirrors omp's `ast_grep`: multi-path search with optional glob,
 * language override, strictness control, contextual selectors, pagination
 * (skip/limit), and optional meta-variable capture. Hashline-style file
 * grouping in the model-facing text; structured details carry the full
 * match list for the TUI.
 *
 * Supported languages: every grammar bundled by pi-ast (Go, TS/JS, Rust,
 * Python, Java, C, C++, Ruby, Swift, Dart, PHP, Kotlin, Haskell, Nix,
 * Markdown, YAML, TOML, JSON, HTML, CSS — plus the additional pi-ast
 * extensions).
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileP = promisify(execFile);

// Absolute /nix/store path — pinned at build time, no PATH dependency.
const PI_RS = "___PI_RS_BIN___";

const STRICTNESS = ["cst", "smart", "ast", "relaxed", "signature", "template"] as const;

interface AstGrepMatch {
  path: string;
  text: string;
  byteStart: number;
  byteEnd: number;
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
  metaVariables?: Record<string, string>;
}

interface AstGrepResult {
  content: string;
  details: {
    matches: AstGrepMatch[];
    totalMatches: number;
    filesWithMatches: number;
    filesSearched: number;
    limitReached: boolean;
    parseErrors: string[] | null;
  };
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "ast_grep",
    label: "AST Grep",
    description:
      "Structural code search via tree-sitter ast-grep patterns. Unlike " +
      "regex grep, ast-grep understands the AST of source code so " +
      "patterns match real code structure regardless of whitespace or " +
      "formatting. Examples: 'console.log($A)' matches every console.log " +
      "call; 'fn $NAME($$$ARGS) { $$$ }' captures every Rust function " +
      "definition with its args and body. " +
      "Use `$VAR` for single-node metavars and `$$$VAR` for variadic " +
      "captures. Pass `selector` to anchor a pattern to a specific " +
      "tree-sitter node kind (e.g. `expression_statement`). " +
      "Supports 30+ languages via pi-ast.",
    parameters: Type.Object({
      pat: Type.String({
        description: "ast-grep structural pattern. See the description for syntax.",
      }),
      paths: Type.Array(Type.String(), {
        description: "Files, directories, or globs to search. Pass one or more.",
        minItems: 1,
      }),
      glob: Type.Optional(Type.String({
        description: "Optional glob filter (relative to each search root, e.g. `**/*.ts`).",
      })),
      language: Type.Optional(Type.String({
        description: "Language override (ts, tsx, js, rust, go, py, java, c, cpp, nix, …). If omitted, inferred from file extension per candidate.",
      })),
      selector: Type.Optional(Type.String({
        description: "Tree-sitter node kind that pins where `pat` applies (e.g. `call_expression`, `expression_statement`).",
      })),
      strictness: Type.Optional(StringEnum(STRICTNESS, {
        description: "Match strictness. Default `smart` balances precision and recall.",
      })),
      limit: Type.Optional(Type.Integer({
        description: "Maximum matches to return (default 50).",
        minimum: 1,
        maximum: 1000,
      })),
      skip: Type.Optional(Type.Integer({
        description: "Skip the first N matches (pagination cursor).",
        minimum: 0,
      })),
      includeMeta: Type.Optional(Type.Boolean({
        description: "Include captured `$VAR` bindings on every match. Off by default — adds noise.",
      })),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
      const argv = ["ast-grep", "--pattern", params.pat];
      for (const p of params.paths) argv.push("--path", p);
      if (params.glob)        argv.push("--glob", params.glob);
      if (params.language)    argv.push("--lang", params.language);
      if (params.selector)    argv.push("--selector", params.selector);
      if (params.strictness)  argv.push("--strictness", params.strictness);
      if (params.limit !== undefined) argv.push("--limit", String(params.limit));
      if (params.skip  !== undefined) argv.push("--offset", String(params.skip));
      if (params.includeMeta)         argv.push("--include-meta");

      let stdout: string;
      try {
        const r = await execFileP(PI_RS, argv, {
          signal,
          maxBuffer: 64 * 1024 * 1024,
          timeout: 60_000,
        });
        stdout = r.stdout;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "ast_grep failed: " + msg }],
          details: { error: "exec_failed", message: msg },
        };
      }

      let parsed: AstGrepResult;
      try {
        parsed = JSON.parse(stdout) as AstGrepResult;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "ast_grep: malformed pi-rs output: " + msg }],
          details: { error: "bad_output", raw: stdout.slice(0, 500) },
        };
      }

      return {
        content: [{ type: "text", text: parsed.content }],
        details: {
          pattern: params.pat,
          paths: params.paths,
          language: params.language,
          ...parsed.details,
        },
      };
    },
  });
}
