/**
 * Pi extension: `ast_edit` tool — structural code rewrites via the pi-rs
 * ast-edit subcommand.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/ast-edit-extension.ts and rebuild.
 *
 * Behavior parity with omp's `ast_edit`: previews structural rewrites by
 * default (so the model can inspect the diff first) and applies them to
 * disk when `apply: true`. Multiple rewrite rules can be passed in one
 * call; pi-rs applies them in order against the same in-memory snapshot
 * per file and rejects overlapping replacements.
 *
 * Workflow:
 *   1. Call with `apply: false` (default) — pi-rs returns the proposed diff.
 *   2. Inspect; if happy, re-issue the call with `apply: true` to write.
 *
 * Use sites: API rewrites, codemods, mechanical refactors that regex can't
 * express safely. For free-form edits, use `edit` instead.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileP = promisify(execFile);

// Absolute /nix/store path — pinned at build time, no PATH dependency.
const PI_RS = "___PI_RS_BIN___";

const STRICTNESS = ["cst", "smart", "ast", "relaxed", "signature", "template"] as const;

interface AstReplaceChange {
  path: string;
  before: string;
  after: string;
  byteStart: number;
  byteEnd: number;
  deletedLength: number;
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
}

interface AstReplaceFileChange {
  path: string;
  count: number;
}

interface AstEditResult {
  content: string;
  details: {
    changes: AstReplaceChange[];
    fileChanges: AstReplaceFileChange[];
    totalReplacements: number;
    filesTouched: number;
    filesSearched: number;
    applied: boolean;
    limitReached: boolean;
    parseErrors: string[] | null;
  };
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "ast_edit",
    label: "AST Edit",
    description:
      "Structural code rewrite via tree-sitter ast-grep patterns. Pass " +
      "one or more `{ pat, out }` rules — every match of `pat` in the " +
      "scanned files is replaced with `out`. Metavariables in `pat` " +
      "(`$VAR`, `$$$ARGS`) are bound and may be substituted in `out`. " +
      "Defaults to a preview (no disk writes); set `apply: true` to " +
      "actually rewrite. Overlapping replacements are rejected. " +
      "For free-form edits, prefer the `edit` tool.",
    parameters: Type.Object({
      ops: Type.Array(
        Type.Object({
          pat: Type.String({ description: "ast-grep pattern to match." }),
          out: Type.String({ description: "Replacement template (uses metavars from `pat`)." }),
        }),
        {
          description: "One or more rewrite rules. Patterns must be unique.",
          minItems: 1,
        },
      ),
      paths: Type.Array(Type.String(), {
        description: "Files, directories, or globs to rewrite. Pass one or more.",
        minItems: 1,
      }),
      glob: Type.Optional(Type.String({
        description: "Optional glob filter (relative to each search root, e.g. `**/*.ts`).",
      })),
      language: Type.Optional(Type.String({
        description: "Language override (ts, rust, go, py, …). Required when `paths` resolves to multiple languages.",
      })),
      selector: Type.Optional(Type.String({
        description: "Tree-sitter node kind that pins where `pat` applies.",
      })),
      strictness: Type.Optional(StringEnum(STRICTNESS, {
        description: "Match strictness. Default `smart`.",
      })),
      apply: Type.Optional(Type.Boolean({
        description: "When true, write changes to disk. Default false (preview only).",
      })),
      maxReplacements: Type.Optional(Type.Integer({
        description: "Cap on total replacements across all files. Default unlimited.",
        minimum: 1,
      })),
      maxFiles: Type.Optional(Type.Integer({
        description: "Cap on distinct files modified in one call. Default 1000.",
        minimum: 1,
      })),
      failOnParseError: Type.Optional(Type.Boolean({
        description: "Abort the whole run on any parse error instead of collecting and continuing.",
      })),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
      const argv = ["ast-edit"];
      // Each rule packed as `pat=>out`. `=>` is unambiguous in ast-grep patterns
      // (no idiomatic pattern uses it as a literal sequence). pi-rs splits on
      // the first occurrence.
      for (const op of params.ops) {
        if (!op.pat) {
          return {
            content: [{ type: "text", text: "ast_edit: every op needs a non-empty `pat`." }],
            details: { error: "empty_pattern" },
          };
        }
        if (op.pat.includes("=>")) {
          return {
            content: [{
              type: "text",
              text: "ast_edit: `pat` cannot contain `=>` (used as the pat/out separator on the wire). Rewrite the pattern.",
            }],
            details: { error: "pat_contains_separator" },
          };
        }
        argv.push("--op", op.pat + "=>" + op.out);
      }
      for (const p of params.paths) argv.push("--path", p);
      if (params.glob)              argv.push("--glob", params.glob);
      if (params.language)          argv.push("--lang", params.language);
      if (params.selector)          argv.push("--selector", params.selector);
      if (params.strictness)        argv.push("--strictness", params.strictness);
      if (params.apply)             argv.push("--apply");
      if (params.maxReplacements !== undefined) argv.push("--max-replacements", String(params.maxReplacements));
      if (params.maxFiles        !== undefined) argv.push("--max-files",        String(params.maxFiles));
      if (params.failOnParseError)              argv.push("--fail-on-parse-error");

      let stdout: string;
      try {
        const r = await execFileP(PI_RS, argv, {
          signal,
          maxBuffer: 64 * 1024 * 1024,
          timeout: 120_000,
        });
        stdout = r.stdout;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "ast_edit failed: " + msg }],
          details: { error: "exec_failed", message: msg },
        };
      }

      let parsed: AstEditResult;
      try {
        parsed = JSON.parse(stdout) as AstEditResult;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "ast_edit: malformed pi-rs output: " + msg }],
          details: { error: "bad_output", raw: stdout.slice(0, 500) },
        };
      }

      return {
        content: [{ type: "text", text: parsed.content }],
        details: {
          ops: params.ops,
          paths: params.paths,
          language: params.language,
          ...parsed.details,
        },
      };
    },
  });
}
