/**
 * Pi extension: `astgrep` tool.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/ast-grep-extension.ts and rebuild.
 *
 * Wraps ast-grep (`sg`) — a fast, polyglot structural search tool.
 * Unlike regex grep, ast-grep understands the AST of source code so
 * patterns match real code structure (function calls, imports, types,
 * etc.) regardless of whitespace or formatting.
 *
 * Supported languages: Go, TypeScript, JS, Rust, Python, Java, C, C++,
 * Ruby, Swift, Dart, PHP, Kotlin, Haskell, Nix, Markdown, YAML, TOML,
 * JSON, HTML, CSS.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileP = promisify(execFile);

// Absolute /nix/store path — pinned at build time, no PATH dependency.
const ASTGREP = "___ASTGREP_BIN___";

/**
 * Result from ast-grep --json (v1 format, ast-grep 0.40+).
 */
interface AstGrepMatch {
  text: string;
  range: {
    byteOffset: { start: number; end: number };
    start: { line: number; column: number };
    end: { line: number; column: number };
  };
  file: string;
  lines: string;
  charCount: { leading: number; trailing: number };
  language: string;
}

/**
 * Parse ast-grep JSON output.
 * ast-grep 0.40+ outputs an array of match objects directly.
 */
function parseAstGrepOutput(stdout: string): AstGrepMatch[] {
  try {
    const parsed = JSON.parse(stdout);
    if (Array.isArray(parsed)) return parsed;
    // Fallback for unexpected formats
    return [];
  } catch {
    return [];
  }
}

/**
 * Format a single match for display.
 */
function formatMatch(m: AstGrepMatch): string {
  const { file, range, text } = m;
  const line = range.start.line + 1; // 0-based → 1-based
  const col = range.start.column + 1;
  const displayText = text.length > 200
    ? text.slice(0, 200) + "..."
    : text;

  return `${file} (${line}:${col})\n  ${displayText}`;
}

/**
 * Format a full result set for the LLM.
 */
function formatResults(
  results: AstGrepMatch[],
  query: string,
  language: string | undefined,
  maxResults: number,
): string {
  if (results.length === 0) {
    return `No matches found.\n\nPattern: ${query}` +
      (language ? ` (language: ${language})` : "");
  }

  const total = results.length;
  const shown = Math.min(total, maxResults);

  const header =
    `Found ${total} match${total !== 1 ? "es" : ""} for ` +
    `"${query}"` +
    (language ? ` in ${language}` : "") +
    `\n\nShowing ${shown} of ${total}:\n`;

  const matches = results
    .slice(0, maxResults)
    .map(formatMatch)
    .join("\n\n");

  const tail =
    total > maxResults
      ? `\n\n... and ${total - maxResults} more matches. ` +
        "Reduce the search scope (use a narrower path or pattern) to see all results."
      : "";

  return header + matches + tail;
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "astgrep",
    label: "AST Grep",
    description:
      "Structural code search using ast-grep. Unlike regex grep, ast-grep " +
      "understands the AST of source code so patterns match real code " +
      "structure (function calls, imports, types, etc.) regardless of " +
      "whitespace or formatting. Supports Go, TypeScript, JS, Rust, " +
      "Python, Java, C, C++, Ruby, Swift, Dart, PHP, Kotlin, Haskell, " +
      "Nix, Markdown, YAML, TOML, JSON, HTML, CSS. Use `sg --help` " +
      "for advanced patterns (tree-sitter selectors).",
    parameters: Type.Object({
      pattern: Type.String({
        description:
          "The search pattern (AST expression or tree-sitter selector). " +
          "Examples: 'console.log($A, $B)', 'import $X from $Y', " +
          "'fn $NAME($PARAMS) { ... }'. Use $VARIABLES for variable " +
          "parts. For complex patterns use tree-sitter syntax: " +
          "(call_expression function: (identifier) @name)'." ,
      }),
      path: Type.Optional(Type.String({
        description:
          "File or directory to search (default: current working directory). " +
          "Use for narrowing the search scope.",
      })),
      language: Type.Optional(Type.String({
        description:
          "Explicit language to parse as (e.g. 'go', 'typescript', 'rust', " +
          "'python', 'java', 'nix'). If omitted, ast-grep infers from file " +
          "extension.",
      })),
      maxResults: Type.Optional(Type.Integer({
        description:
          "Maximum number of results to return (default 50).",
        minimum: 1,
        maximum: 500,
      })),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
      const maxResults = params.maxResults ?? 50;
      const args = [
        "--json",
        "--pattern",
        params.pattern,
      ];

      if (params.language) {
        args.push("--lang", params.language);
      }

      if (params.path) {
        args.push(params.path);
      }

      let stdout: string;
      try {
        const r = await execFileP(
          ASTGREP,
          args,
          {
            signal,
            maxBuffer: 16 * 1024 * 1024,
            timeout: 30000,
          },
        );
        stdout = r.stdout;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [
            {
              type: "text",
              text: "ast-grep failed: " + msg,
            },
          ],
          details: { error: "exec_failed", message: msg },
        };
      }

      if (!stdout.trim()) {
        return {
          content: [
            {
              type: "text",
              text: formatResults([], params.pattern, params.language, maxResults),
            },
          ],
          details: {
            pattern: params.pattern,
            count: 0,
          },
        };
      }

      const results = parseAstGrepOutput(stdout);

      return {
        content: [
          {
            type: "text",
            text: formatResults(
              results,
              params.pattern,
              params.language,
              maxResults,
            ),
          },
        ],
        details: {
          pattern: params.pattern,
          language: params.language,
          count: results.length,
          maxResults,
        },
      };
    },
  });
}
