/**
 * Pi extension: single `lsp` tool with 14 actions.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/lsp-extension.ts and rebuild.
 *
 * Spawns one language server per (binary, project root) on first request
 * and reuses it for subsequent calls. Implements a substantial subset of
 * LSP JSON-RPC 2.0 so the agent has IDE-level intelligence:
 *
 *   action            LSP method                       writes
 *   ────────────────  ───────────────────────────────  ──────
 *   diagnostics       (cached + waitForNextDiagnostics)  no
 *   hover             textDocument/hover                no
 *   definition        textDocument/definition           no
 *   type_definition   textDocument/typeDefinition       no
 *   implementation    textDocument/implementation       no
 *   references        textDocument/references           no
 *   symbols           textDocument/documentSymbol       no
 *                     workspace/symbol (when file=*)    no
 *   code_actions      textDocument/codeAction           apply=true ⇒ yes
 *                     codeAction/resolve                applies WorkspaceEdit
 *                     workspace/executeCommand
 *   rename            textDocument/rename               apply=true ⇒ yes
 *   rename_file       workspace/willRenameFiles         apply=true ⇒ yes
 *                     + fs.rename
 *                     + workspace/didRenameFiles
 *   status            (no LSP call)                     no
 *   reload            (kill + respawn)                  no
 *   capabilities      (cached from initialize)          no
 *   request           (arbitrary method via payload)    server-defined
 *
 * Supported languages:
 *   Go      (.go)                              → gopls
 *   TS/JS   (.ts .tsx .js .jsx .mts .cts)      → typescript-language-server
 *   Rust    (.rs)                              → rust-analyzer
 *   Nix     (.nix)                             → nil
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { Buffer } from "node:buffer";
import { pathToFileURL, fileURLToPath } from "node:url";
import { readFile, writeFile, stat, rename as fsRename, mkdir, readdir, rm } from "node:fs/promises";
import { resolve as resolvePath, dirname, join as joinPath, relative as relativePath } from "node:path";

// Absolute /nix/store paths — replaced by Nix at build time.
const GOLANG_LSP    = "___GOLANG_LSP___";
const TS_LSP        = "___TS_LSP___";
const RUST_ANALYZER = "___RUST_ANALYZER___";
const NIX_LSP       = "___NIX_LSP___";

const DEFAULT_REQUEST_TIMEOUT_MS = 15000;
const INIT_TIMEOUT_MS             = 10000;
const DIAGNOSTICS_WAIT_MS         = 2500;
const MAX_RENAME_PAIRS            = 5000;
const ROOT_MARKERS = ["go.mod", "Cargo.toml", "package.json", "tsconfig.json", "flake.nix", ".git"];

interface ServerSpec {
  bin: string;
  args: string[];
  languageId: string;
  name: string;
}

const SERVER_MAP: Record<string, ServerSpec> = {
  ".go":  { bin: GOLANG_LSP,    args: [],          languageId: "go",               name: "gopls" },
  ".ts":  { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript",       name: "ts-ls" },
  ".tsx": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescriptreact",  name: "ts-ls" },
  ".js":  { bin: TS_LSP,        args: ["--stdio"], languageId: "javascript",       name: "ts-ls" },
  ".jsx": { bin: TS_LSP,        args: ["--stdio"], languageId: "javascriptreact",  name: "ts-ls" },
  ".mts": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript",       name: "ts-ls" },
  ".cts": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript",       name: "ts-ls" },
  ".rs":  { bin: RUST_ANALYZER, args: [],          languageId: "rust",             name: "rust-analyzer" },
  ".nix": { bin: NIX_LSP,       args: [],          languageId: "nix",              name: "nil" },
};

const SUPPORTED_LIST =
  ".go (gopls), .ts/.tsx/.js/.jsx/.mts/.cts (typescript-language-server), " +
  ".rs (rust-analyzer), .nix (nil)";



// ─── LSP protocol types (minimal) ───────────────────────────────────────────

interface Position { line: number; character: number; }
interface Range { start: Position; end: Position; }
interface Location { uri: string; range: Range; }
interface LocationLink { targetUri: string; targetRange: Range; targetSelectionRange: Range; }
interface TextEdit { range: Range; newText: string; }
interface CreateFileOp { kind: "create"; uri: string; options?: { overwrite?: boolean; ignoreIfExists?: boolean } }
interface RenameFileOp { kind: "rename"; oldUri: string; newUri: string; options?: { overwrite?: boolean; ignoreIfExists?: boolean } }
interface DeleteFileOp { kind: "delete"; uri: string; options?: { recursive?: boolean; ignoreIfNotExists?: boolean } }
interface TextDocumentEdit {
  textDocument: { uri: string; version?: number | null };
  edits: TextEdit[];
}
type DocumentChange = TextDocumentEdit | CreateFileOp | RenameFileOp | DeleteFileOp;
interface WorkspaceEdit {
  changes?: Record<string, TextEdit[]>;
  documentChanges?: DocumentChange[];
}

interface LspDiagnostic {
  severity?: number;
  message: string;
  source?: string;
  code?: string | number;
  range: Range;
}

interface CodeAction {
  title: string;
  kind?: string;
  diagnostics?: LspDiagnostic[];
  isPreferred?: boolean;
  disabled?: { reason: string };
  edit?: WorkspaceEdit;
  command?: { title: string; command: string; arguments?: unknown[] };
  data?: unknown;
}
type CodeActionOrCommand = CodeAction | { title: string; command: string; arguments?: unknown[] };

interface SymbolInfo {
  name: string;
  kind: number;
  range?: Range;
  selectionRange?: Range;
  location?: Location;
  containerName?: string;
  children?: SymbolInfo[];
}

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject:  (err: Error) => void;
  method:  string;
}

interface ServerCapabilities {
  renameProvider?: boolean | { prepareProvider?: boolean };
  codeActionProvider?: boolean | { resolveProvider?: boolean; codeActionKinds?: string[] };
  hoverProvider?: boolean;
  definitionProvider?: boolean;
  typeDefinitionProvider?: boolean;
  implementationProvider?: boolean;
  referencesProvider?: boolean;
  documentSymbolProvider?: boolean;
  workspaceSymbolProvider?: boolean;
  workspace?: {
    fileOperations?: {
      willRename?: unknown;
      didRename?: unknown;
    };
  };
  [key: string]: unknown;
}

// ─── LSP client ─────────────────────────────────────────────────────────────

class LspClient {
  private proc: ChildProcessWithoutNullStreams;
  private pending = new Map<number, PendingRequest>();
  private nextId = 1;
  private stdoutBuf: Buffer = Buffer.alloc(0);
  private ready = false;
  private openDocs = new Map<string, { version: number; text: string; languageId: string }>();
  diagnostics = new Map<string, LspDiagnostic[]>();
  private diagWaiters = new Map<string, () => void>();
  private fatalError: Error | null = null;
  readonly bin: string;
  readonly serverName: string;
  readonly projectRoot: string;
  private rootUri: string;
  serverCapabilities: ServerCapabilities = {};
  startedAt = Date.now();
  onExit: (() => void) | null = null;

  constructor(spec: ServerSpec, projectRoot: string) {
    this.bin = spec.bin;
    this.serverName = spec.name;
    this.projectRoot = projectRoot;
    this.rootUri = pathToFileURL(projectRoot + "/").href;

    this.proc = spawn(spec.bin, spec.args, {
      stdio: ["pipe", "pipe", "pipe"],
      cwd: projectRoot,
    });

    this.proc.stdout.on("data", (c: Buffer) => this.onData(c));
    this.proc.stderr.on("data", () => { /* discard chatter */ });
    this.proc.on("error", (err) => {
      this.fatalError = err;
      this.failAll(err);
      if (this.onExit) this.onExit();
    });
    this.proc.on("close", (code) => {
      const err = this.fatalError ?? new Error(
        "LSP server '" + spec.bin + "' exited (code " + code + ")",
      );
      this.fatalError = err;
      this.ready = false;
      this.failAll(err);
      if (this.onExit) this.onExit();
    });
    this.proc.stdin.on("error", () => { /* surfaced via 'close' */ });
  }

  private failAll(err: Error) {
    for (const [, p] of this.pending) {
      p.reject(new Error("LSP " + p.method + " failed: " + err.message));
    }
    this.pending.clear();
    for (const [, w] of this.diagWaiters) w();
    this.diagWaiters.clear();
  }

  async init(): Promise<void> {
    if (this.fatalError) throw this.fatalError;
    const result = await this.sendRequest<{ capabilities?: ServerCapabilities }>("initialize", {
      processId: typeof process !== "undefined" ? process.pid : null,
      rootUri: this.rootUri,
      workspaceFolders: [{ uri: this.rootUri, name: "root" }],
      capabilities: {
        textDocument: {
          publishDiagnostics: { relatedInformation: true },
          synchronization: {
            dynamicRegistration: false,
            willSave: false,
            didSave: false,
          },
          hover: { contentFormat: ["plaintext", "markdown"] },
          definition: { linkSupport: true },
          typeDefinition: { linkSupport: true },
          implementation: { linkSupport: true },
          references: {},
          documentSymbol: { hierarchicalDocumentSymbolSupport: true },
          formatting: {},
          rename: { prepareSupport: true },
          codeAction: {
            codeActionLiteralSupport: {
              codeActionKind: {
                valueSet: [
                  "", "quickfix", "refactor", "refactor.extract",
                  "refactor.inline", "refactor.rewrite",
                  "source", "source.organizeImports", "source.fixAll",
                ],
              },
            },
            isPreferredSupport: true,
            disabledSupport: true,
            dataSupport: true,
            resolveSupport: { properties: ["edit"] },
          },
        },
        workspace: {
          workspaceFolders: true,
          configuration: true,
          symbol: { dynamicRegistration: false },
          executeCommand: {},
          fileOperations: {
            willRename: true,
            didRename: true,
          },
          workspaceEdit: {
            documentChanges: true,
            resourceOperations: ["create", "rename", "delete"],
          },
        },
      },
      clientInfo: { name: "pi-lsp", version: "0.3" },
    }, INIT_TIMEOUT_MS);
    this.serverCapabilities = result?.capabilities ?? {};
    this.ready = true;
    this.sendNotification("initialized", {});
  }

  // ── Public API ────────────────────────────────────────────────────────────

  request<T>(method: string, params: unknown, timeoutMs = DEFAULT_REQUEST_TIMEOUT_MS): Promise<T> {
    if (!this.ready) return Promise.reject(new Error("LSP client not initialized"));
    return this.sendRequest<T>(method, params, timeoutMs);
  }

  /** Send a notification (no response). */
  notify(method: string, params: unknown): void {
    this.sendNotification(method, params);
  }

  async ensureOpen(filepath: string, languageId: string): Promise<string> {
    const uri = pathToFileURL(filepath).href;
    let text: string;
    try {
      text = await readFile(filepath, "utf8");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error("cannot read " + filepath + ": " + msg);
    }
    const existing = this.openDocs.get(uri);
    if (existing) {
      if (existing.text === text) return uri;
      const newVersion = existing.version + 1;
      this.sendNotification("textDocument/didChange", {
        textDocument: { uri, version: newVersion },
        contentChanges: [{ text }],
      });
      this.openDocs.set(uri, { version: newVersion, text, languageId: existing.languageId });
    } else {
      this.sendNotification("textDocument/didOpen", {
        textDocument: { uri, languageId, version: 1, text },
      });
      this.openDocs.set(uri, { version: 1, text, languageId });
    }
    return uri;
  }

  /** Invalidate the cached version of `uri` so the next ensureOpen re-syncs. */
  invalidate(uri: string): void {
    this.openDocs.delete(uri);
  }

  /** True when the server has explicitly published diagnostics for `uri`. */
  hasDiagnosticsFor(uri: string): boolean {
    return this.diagnostics.has(uri);
  }

  getDiagnostics(uri: string): LspDiagnostic[] {
    return this.diagnostics.get(uri) ?? [];
  }

  /**
   * Resolves on the next `publishDiagnostics` for `uri`, or after `timeoutMs`.
   * Must be installed *before* triggering didOpen/didChange.
   */
  waitForNextDiagnostics(uri: string, timeoutMs: number): Promise<void> {
    return new Promise<void>((resolve) => {
      let done = false;
      const finish = () => {
        if (done) return;
        done = true;
        if (this.diagWaiters.get(uri) === finish) this.diagWaiters.delete(uri);
        resolve();
      };
      this.diagWaiters.set(uri, finish);
      setTimeout(finish, timeoutMs);
    });
  }

  shutdown() {
    try { this.proc.kill(); } catch { /* ignore */ }
  }

  // ── Internals ─────────────────────────────────────────────────────────────

  private sendRequest<T>(method: string, params: unknown, timeoutMs: number): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      if (this.fatalError) { reject(this.fatalError); return; }
      const id = this.nextId++;
      const timer = setTimeout(() => {
        if (this.pending.delete(id)) {
          reject(new Error("LSP " + method + " timed out after " + timeoutMs + "ms"));
        }
      }, timeoutMs);
      this.pending.set(id, {
        resolve: (v) => { clearTimeout(timer); resolve(v as T); },
        reject:  (e) => { clearTimeout(timer); reject(e); },
        method,
      });
      this.write({ jsonrpc: "2.0", method, params: params ?? {}, id });
    });
  }

  private onData(chunk: Buffer) {
    this.stdoutBuf = Buffer.concat([this.stdoutBuf, chunk]);
    while (true) {
      const headerEnd = this.stdoutBuf.indexOf("\r\n\r\n");
      if (headerEnd === -1) return;
      const header = this.stdoutBuf.slice(0, headerEnd).toString("utf8");
      const m = /Content-Length:\s*(\d+)/i.exec(header);
      if (!m) {
        this.stdoutBuf = this.stdoutBuf.slice(headerEnd + 4);
        continue;
      }
      const len = parseInt(m[1], 10);
      const bodyStart = headerEnd + 4;
      if (this.stdoutBuf.length < bodyStart + len) return;
      const body = this.stdoutBuf.slice(bodyStart, bodyStart + len).toString("utf8");
      this.stdoutBuf = this.stdoutBuf.slice(bodyStart + len);
      try {
        this.handleMessage(JSON.parse(body));
      } catch { /* ignore malformed JSON */ }
    }
  }

  private handleMessage(msg: any) {
    if (
      (typeof msg.id === "number" || typeof msg.id === "string") &&
      msg.method === undefined
    ) {
      const id = typeof msg.id === "number" ? msg.id : parseInt(msg.id as string, 10);
      const req = this.pending.get(id);
      if (!req) return;
      this.pending.delete(id);
      if (msg.error) {
        const m =
          typeof msg.error === "object" && msg.error && typeof msg.error.message === "string"
            ? msg.error.message
            : JSON.stringify(msg.error);
        const err = new Error("LSP " + req.method + ": " + m) as Error & { code?: number };
        if (typeof msg.error === "object" && msg.error && typeof msg.error.code === "number") {
          err.code = msg.error.code;
        }
        req.reject(err);
      } else {
        req.resolve(msg.result);
      }
      return;
    }

    if (typeof msg.method !== "string") return;

    if (msg.method === "textDocument/publishDiagnostics" && msg.params) {
      const uri = msg.params.uri;
      if (typeof uri !== "string") return;
      const diags = Array.isArray(msg.params.diagnostics)
        ? (msg.params.diagnostics as LspDiagnostic[])
        : [];
      this.diagnostics.set(uri, diags);
      const w = this.diagWaiters.get(uri);
      if (w) w();
      return;
    }

    // Server → client request (must respond)
    if (msg.id !== undefined && msg.id !== null) {
      // workspace/applyEdit needs async work (apply edits to disk) before
      // we can honestly report success. Handle it out-of-band so the rest
      // of the message loop isn't blocked.
      if (msg.method === "workspace/applyEdit") {
        const reqId = msg.id as number | string;
        const editParam = (msg.params as { edit?: WorkspaceEdit; label?: string } | undefined)?.edit;
        if (!editParam) {
          this.respond(reqId, { applied: false, failureReason: "missing edit" });
        } else {
          // Fire-and-respond: invoke the configured applicator, then respond.
          // Per LSP spec, `applied` means "could be applied", not "changed something".
          // An empty edit is still successfully applied. Only catch genuine failures.
          applyWorkspaceEdit(editParam, process.cwd(), uri => { void invalidateAcrossClients(uri); })
            .then(() => {
              this.respond(reqId, { applied: true });
            })
            .catch(err => {
              const msg2 = err instanceof Error ? err.message : String(err);
              this.respond(reqId, { applied: false, failureReason: msg2 });
            });
        }
        return;
      }
      let result: unknown = null;
      if (msg.method === "workspace/configuration") {
        const n = Array.isArray(msg.params?.items) ? msg.params.items.length : 0;
        result = new Array(n).fill(null);
      } else if (msg.method === "workspace/workspaceFolders") {
        result = [{ uri: this.rootUri, name: "root" }];
      }
      this.respond(msg.id as number | string, result);
    }
    // Pure notifications (window/logMessage, $/progress) are ignored.
  }

  private respond(id: number | string, result: unknown) {
    this.write({ jsonrpc: "2.0", id, result });
  }

  private sendNotification(method: string, params: unknown) {
    this.write({ jsonrpc: "2.0", method, params: params ?? {} });
  }

  private write(payload: unknown) {
    if (this.fatalError) return;
    const json = JSON.stringify(payload);
    const header = "Content-Length: " + Buffer.byteLength(json, "utf8") + "\r\n\r\n";
    try {
      this.proc.stdin.write(header + json);
    } catch (err) {
      this.fatalError = err instanceof Error ? err : new Error(String(err));
    }
  }
}

// ─── Client pool ────────────────────────────────────────────────────────────

function clientKey(spec: ServerSpec, projectRoot: string): string {
  return spec.bin + "@" + projectRoot;
}

const clients = new Map<string, Promise<LspClient>>();

async function getClient(spec: ServerSpec, projectRoot: string): Promise<LspClient> {
  const key = clientKey(spec, projectRoot);
  let existing = clients.get(key);
  if (existing) return existing;

  const created = (async () => {
    const c = new LspClient(spec, projectRoot);
    c.onExit = () => {
      if (clients.get(key) === created) clients.delete(key);
    };
    try {
      await c.init();
    } catch (err) {
      clients.delete(key);
      c.shutdown();
      throw err;
    }
    return c;
  })();
  clients.set(key, created);
  return created;
}

function dropClient(key: string): void {
  clients.delete(key);
}

/** Snapshot only-settled clients. Used by `status`, `request`, and workspace fan-out. */
async function listSettledClients(): Promise<Array<{ key: string; client: LspClient }>> {
  const settled: Array<{ key: string; client: LspClient }> = [];
  for (const [key, promise] of clients) {
    try {
      // Race against an already-resolved promise; if not resolved, skip.
      const c = await Promise.race([
        promise,
        new Promise<null>(resolve => setImmediate(() => resolve(null))),
      ]);
      if (c) settled.push({ key, client: c as LspClient });
    } catch { /* skip failed clients */ }
  }
  return settled;
}

// ─── Project root discovery ─────────────────────────────────────────────────

const projectRootCache = new Map<string, string>();

async function findProjectRoot(filepath: string): Promise<string> {
  let dir = dirname(resolvePath(filepath));
  for (let i = 0; i < 32; i++) {
    for (const m of ROOT_MARKERS) {
      try {
        await stat(dir + "/" + m);
        return dir;
      } catch { /* not found */ }
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return dirname(resolvePath(filepath));
}

async function getProjectRoot(filepath: string): Promise<string> {
  const abs = resolvePath(filepath);
  let root = projectRootCache.get(abs);
  if (!root) {
    root = await findProjectRoot(abs);
    projectRootCache.set(abs, root);
  }
  return root;
}

// ─── Server lookup ─────────────────────────────────────────────────────────

function findServerForFile(filepath: string): ServerSpec | null {
  const lower = filepath.toLowerCase();
  for (const ext of [".tsx", ".jsx", ".mts", ".cts"]) {
    if (lower.endsWith(ext)) return SERVER_MAP[ext];
  }
  const dotIdx = lower.lastIndexOf(".");
  if (dotIdx === -1) return null;
  return SERVER_MAP[lower.slice(dotIdx)] ?? null;
}

// ─── URI / path conversion ─────────────────────────────────────────────────

function fileToUri(filepath: string): string {
  return pathToFileURL(resolvePath(filepath)).href;
}

function uriToPath(uri: string): string {
  try { return fileURLToPath(uri); } catch { return uri; }
}

function formatRelativePath(absolute: string, cwd: string): string {
  const rel = relativePath(cwd, absolute);
  if (!rel || rel.startsWith("..")) return absolute;
  return rel;
}

// ─── Symbol resolution (line + substring → column) ─────────────────────────

const BARE_IDENTIFIER_RE = /^[A-Za-z_][\w]*$/;
const IDENTIFIER_CHAR_RE = /[A-Za-z0-9_$]/;

function findSymbolMatchIndexes(lineText: string, symbol: string, caseInsensitive = false): number[] {
  if (symbol.length === 0) return [];
  const haystack = caseInsensitive ? lineText.toLowerCase() : lineText;
  const needle   = caseInsensitive ? symbol.toLowerCase()   : symbol;
  const requireWordBoundary = BARE_IDENTIFIER_RE.test(symbol);
  const indexes: number[] = [];
  let fromIndex = 0;
  while (fromIndex <= haystack.length - needle.length) {
    const idx = haystack.indexOf(needle, fromIndex);
    if (idx === -1) break;
    if (requireWordBoundary) {
      const before = idx > 0 ? haystack[idx - 1] : "";
      const afterIdx = idx + needle.length;
      const after = afterIdx < haystack.length ? haystack[afterIdx] : "";
      if (IDENTIFIER_CHAR_RE.test(before) || IDENTIFIER_CHAR_RE.test(after)) {
        fromIndex = idx + 1;
        continue;
      }
    }
    indexes.push(idx);
    fromIndex = idx + needle.length;
  }
  return indexes;
}

function firstNonWhitespaceColumn(lineText: string): number {
  const match = lineText.match(/\S/);
  return match ? (match.index ?? 0) : 0;
}

/**
 * Parses `name` or `name#N` (1-indexed occurrence on the target line).
 * Greedy match on `.+` so `#field#2` parses as symbol=`#field`, occurrence 2.
 */
function parseSymbolSpec(spec: string): { symbol: string; occurrence: number } {
  const m = spec.match(/^(.+)#(\d+)$/);
  if (!m) return { symbol: spec, occurrence: 1 };
  return { symbol: m[1], occurrence: Math.max(1, parseInt(m[2], 10)) };
}

async function resolveSymbolColumn(filepath: string, line: number, symbolSpec?: string): Promise<number> {
  const lineNumber = Math.max(1, line);
  const text = await readFile(filepath, "utf8");
  const lines = text.split("\n");
  const target = lines[lineNumber - 1] ?? "";
  if (!symbolSpec) return firstNonWhitespaceColumn(target);

  const { symbol, occurrence } = parseSymbolSpec(symbolSpec);
  const exact = findSymbolMatchIndexes(target, symbol, false);
  const fallback = exact.length > 0 ? exact : findSymbolMatchIndexes(target, symbol, true);
  if (fallback.length === 0) {
    throw new Error(`Symbol "${symbol}" not found on line ${lineNumber} of ${filepath}`);
  }
  if (occurrence > fallback.length) {
    throw new Error(
      `Symbol "${symbol}" occurrence ${occurrence} is out of bounds on line ${lineNumber} (found ${fallback.length})`,
    );
  }
  return fallback[occurrence - 1];
}

// ─── Workspace edit application ────────────────────────────────────────────

function comparePosition(a: Position, b: Position): number {
  return a.line === b.line ? a.character - b.character : a.line - b.line;
}

function formatRange(r: Range): string {
  return `${r.start.line + 1}:${r.start.character + 1}-${r.end.line + 1}:${r.end.character + 1}`;
}

/** Apply text edits to an in-memory string. Edits are applied bottom-up. */
function applyTextEditsToString(content: string, edits: TextEdit[]): string {
  const lines = content.split("\n");
  const sorted = [...edits].sort((a, b) => {
    if (a.range.start.line !== b.range.start.line) {
      return b.range.start.line - a.range.start.line;
    }
    return b.range.start.character - a.range.start.character;
  });

  for (let i = 0; i < sorted.length - 1; i++) {
    const later = sorted[i].range;
    const earlier = sorted[i + 1].range;
    if (comparePosition(earlier.end, later.start) > 0) {
      throw new Error(
        `overlapping LSP edits: ${formatRange(earlier)} conflicts with ${formatRange(later)}`,
      );
    }
  }

  for (const edit of sorted) {
    const { start, end } = edit.range;
    if (start.line === end.line) {
      const line = lines[start.line] ?? "";
      lines[start.line] = line.slice(0, start.character) + edit.newText + line.slice(end.character);
    } else {
      const startLine = lines[start.line] ?? "";
      const endLine = lines[end.line] ?? "";
      const merged = startLine.slice(0, start.character) + edit.newText + endLine.slice(end.character);
      lines.splice(start.line, end.line - start.line + 1, ...merged.split("\n"));
    }
  }
  return lines.join("\n");
}

async function applyTextEditsToFile(filePath: string, edits: TextEdit[]): Promise<void> {
  const content = await readFile(filePath, "utf8");
  const result = applyTextEditsToString(content, edits);
  await writeFile(filePath, result, "utf8");
}

function flattenWorkspaceTextEdits(edit: WorkspaceEdit): Map<string, TextEdit[]> {
  const out = new Map<string, TextEdit[]>();
  const push = (uri: string, edits: TextEdit[]) => {
    if (edits.length === 0) return;
    const prev = out.get(uri);
    if (prev) prev.push(...edits);
    else out.set(uri, [...edits]);
  };
  if (edit.changes) {
    for (const uri in edit.changes) push(uri, edit.changes[uri] ?? []);
  }
  if (edit.documentChanges) {
    for (const change of edit.documentChanges) {
      if ("textDocument" in change && Array.isArray((change as TextDocumentEdit).edits)) {
        const tdc = change as TextDocumentEdit;
        const tes = tdc.edits.filter((e): e is TextEdit => !!e && "range" in e && "newText" in e);
        push(tdc.textDocument.uri, tes);
      }
    }
  }
  return out;
}

async function applyWorkspaceEdit(
  edit: WorkspaceEdit,
  cwd: string,
  invalidateClients: (uri: string) => void,
): Promise<string[]> {
  const applied: string[] = [];

  // Coalesce text edits per URI so a single snapshot is mutated once.
  const byUri = flattenWorkspaceTextEdits(edit);
  for (const [uri, edits] of byUri) {
    const filePath = uriToPath(uri);
    await applyTextEditsToFile(filePath, edits);
    invalidateClients(uri);
    applied.push(`Applied ${edits.length} edit(s) to ${formatRelativePath(filePath, cwd)}`);
  }

  // Resource operations preserve their declared order.
  if (edit.documentChanges) {
    for (const change of edit.documentChanges) {
      if (!("kind" in change) || !change.kind) continue;
      if (change.kind === "create") {
        const create = change as CreateFileOp;
        const filePath = uriToPath(create.uri);
        const opts = create.options ?? {};
        let exists = false;
        try { await stat(filePath); exists = true; } catch { /* not present */ }
        if (exists && opts.ignoreIfExists && !opts.overwrite) {
          applied.push(`Skipped create (exists): ${formatRelativePath(filePath, cwd)}`);
          continue;
        }
        await mkdir(dirname(filePath), { recursive: true });
        await writeFile(filePath, "", "utf8");
        applied.push(`Created ${formatRelativePath(filePath, cwd)}`);
      } else if (change.kind === "rename") {
        const renameOp = change as RenameFileOp;
        const oldPath = uriToPath(renameOp.oldUri);
        const newPath = uriToPath(renameOp.newUri);
        await mkdir(dirname(newPath), { recursive: true });
        await fsRename(oldPath, newPath);
        invalidateClients(renameOp.oldUri);
        invalidateClients(renameOp.newUri);
        applied.push(
          `Renamed ${formatRelativePath(oldPath, cwd)} → ${formatRelativePath(newPath, cwd)}`,
        );
      } else if (change.kind === "delete") {
        const del = change as DeleteFileOp;
        const filePath = uriToPath(del.uri);
        const opts = del.options ?? {};
        try {
          await rm(filePath, { recursive: opts.recursive ?? false });
          invalidateClients(del.uri);
          applied.push(`Deleted ${formatRelativePath(filePath, cwd)}`);
        } catch (err) {
          if (opts.ignoreIfNotExists) {
            applied.push(`Skipped delete (missing): ${formatRelativePath(filePath, cwd)}`);
          } else {
            throw err;
          }
        }
      }
    }
  }

  return applied;
}

// ─── Formatters ────────────────────────────────────────────────────────────

const SEVERITY_NAMES = ["", "Error", "Warning", "Info", "Hint"];

function fmtDiagnostic(d: LspDiagnostic, filepath: string): string {
  const sev = d.severity !== undefined
    ? (SEVERITY_NAMES[Math.min(d.severity, 4)] ?? "Unknown")
    : "Error";
  const line = (d.range?.start?.line ?? 0) + 1;
  const col  = (d.range?.start?.character ?? 0) + 1;
  const src  = d.source ? " [" + d.source + "]" : "";
  const code = d.code !== undefined ? " (" + String(d.code) + ")" : "";
  return sev + " " + filepath + ":" + line + ":" + col + src + code + " — " + d.message;
}

function fmtLocation(loc: Location, cwd: string): string {
  const file = formatRelativePath(uriToPath(loc.uri), cwd);
  const line = loc.range.start.line + 1;
  const col  = loc.range.start.character + 1;
  return `${file}:${line}:${col}`;
}

function normalizeLocations(result: unknown): Location[] {
  if (!result) return [];
  const arr = Array.isArray(result) ? result : [result];
  const out: Location[] = [];
  for (const item of arr) {
    if (!item || typeof item !== "object") continue;
    const obj = item as Partial<Location & LocationLink>;
    if (obj.targetUri && obj.targetRange) {
      out.push({ uri: obj.targetUri, range: obj.targetRange });
    } else if (obj.uri && obj.range) {
      out.push({ uri: obj.uri, range: obj.range });
    }
  }
  return out;
}

function fmtHoverContents(contents: unknown): string {
  if (!contents) return "";
  if (typeof contents === "string") return contents;
  if (Array.isArray(contents)) {
    return contents.map(fmtHoverContents).filter(Boolean).join("\n\n");
  }
  if (typeof contents === "object") {
    const c = contents as { value?: string; language?: string };
    if (typeof c.value === "string") {
      if (typeof c.language === "string") return "```" + c.language + "\n" + c.value + "\n```";
      return c.value;
    }
  }
  return "";
}

const SYMBOL_KIND_NAMES = [
  "", "File", "Module", "Namespace", "Package", "Class", "Method", "Property",
  "Field", "Constructor", "Enum", "Interface", "Function", "Variable", "Constant",
  "String", "Number", "Boolean", "Array", "Object", "Key", "Null", "EnumMember",
  "Struct", "Event", "Operator", "TypeParameter",
];

function fmtSymbolKind(kind: unknown): string {
  const n = typeof kind === "number" ? kind : 0;
  return SYMBOL_KIND_NAMES[n] ?? "Unknown";
}

function fmtDocumentSymbols(result: unknown, filepath: string): string {
  if (!Array.isArray(result) || result.length === 0) return "No symbols found in file.";
  const lines: string[] = [];
  const visit = (items: SymbolInfo[], depth: number) => {
    for (const s of items) {
      if (!s || typeof s !== "object") continue;
      const indent = "  ".repeat(depth);
      const arrow  = depth > 0 ? "└ " : "";
      const name   = s.name ?? "?";
      const kind   = fmtSymbolKind(s.kind);
      const range  = s.range ?? s.location?.range;
      const lineStr = range?.start?.line !== undefined
        ? " (line " + (range.start.line + 1) + ")"
        : "";
      let suffix = lineStr;
      const uri = s.location?.uri;
      if (uri) {
        const p = uriToPath(uri);
        if (p !== filepath) suffix = " [" + p + "]" + lineStr;
      }
      lines.push(indent + arrow + name + " [" + kind + "]" + suffix);
      if (Array.isArray(s.children)) visit(s.children, depth + 1);
    }
  };
  visit(result as SymbolInfo[], 0);
  return lines.join("\n");
}

function fmtWorkspaceEdit(edit: WorkspaceEdit, cwd: string): string[] {
  const out: string[] = [];
  if (edit.changes) {
    for (const [uri, edits] of Object.entries(edit.changes)) {
      const file = formatRelativePath(uriToPath(uri), cwd);
      out.push(`${file}: ${edits.length} edit${edits.length !== 1 ? "s" : ""}`);
    }
  }
  if (edit.documentChanges) {
    for (const change of edit.documentChanges) {
      if ("textDocument" in change && Array.isArray((change as TextDocumentEdit).edits)) {
        const tdc = change as TextDocumentEdit;
        const file = formatRelativePath(uriToPath(tdc.textDocument.uri), cwd);
        out.push(`${file}: ${tdc.edits.length} edit${tdc.edits.length !== 1 ? "s" : ""}`);
      } else if ("kind" in change) {
        switch (change.kind) {
          case "create":
            out.push(`CREATE: ${formatRelativePath(uriToPath((change as CreateFileOp).uri), cwd)}`);
            break;
          case "rename": {
            const r = change as RenameFileOp;
            out.push(
              `RENAME: ${formatRelativePath(uriToPath(r.oldUri), cwd)} → ${formatRelativePath(uriToPath(r.newUri), cwd)}`,
            );
            break;
          }
          case "delete":
            out.push(`DELETE: ${formatRelativePath(uriToPath((change as DeleteFileOp).uri), cwd)}`);
            break;
        }
      }
    }
  }
  return out;
}

function fmtCodeAction(action: CodeActionOrCommand, index: number): string {
  const kind = "kind" in action && action.kind ? action.kind : "action";
  const pref = "isPreferred" in action && (action as CodeAction).isPreferred ? " (preferred)" : "";
  const dis  = "disabled" in action && (action as CodeAction).disabled
    ? ` (disabled: ${(action as CodeAction).disabled!.reason})` : "";
  return `${index}: [${kind}] ${action.title}${pref}${dis}`;
}

// ─── Cross-client URI invalidation ─────────────────────────────────────────

async function invalidateAcrossClients(uri: string): Promise<void> {
  for (const [, p] of clients) {
    try {
      const c = await Promise.race([
        p,
        new Promise<null>(resolve => setImmediate(() => resolve(null))),
      ]);
      if (c) (c as LspClient).invalidate(uri);
    } catch { /* skip failed clients */ }
  }
}

// ─── rename_file enumeration ───────────────────────────────────────────────

async function enumerateRenamePairs(
  source: string,
  dest: string,
): Promise<{ pairs: Array<{ oldUri: string; newUri: string }>; exceeded: boolean }> {
  const srcStat = await stat(source);
  if (srcStat.isFile()) {
    return { pairs: [{ oldUri: fileToUri(source), newUri: fileToUri(dest) }], exceeded: false };
  }
  const pairs: Array<{ oldUri: string; newUri: string }> = [];
  const stack = [source];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const oldPath = joinPath(dir, entry.name);
      const newPath = joinPath(dest, relativePath(source, oldPath));
      if (entry.isDirectory()) {
        stack.push(oldPath);
      } else if (entry.isFile()) {
        pairs.push({ oldUri: fileToUri(oldPath), newUri: fileToUri(newPath) });
        if (pairs.length > MAX_RENAME_PAIRS) return { pairs, exceeded: true };
      }
    }
  }
  return { pairs, exceeded: false };
}

// ─── Code-action application ───────────────────────────────────────────────

function isCommandOnly(item: CodeActionOrCommand): item is { title: string; command: string; arguments?: unknown[] } {
  return typeof (item as { command?: unknown }).command === "string";
}

async function applyCodeActionOrCommand(
  item: CodeActionOrCommand,
  client: LspClient,
  cwd: string,
): Promise<{ title: string; edits: string[]; commands: string[] } | null> {
  if (isCommandOnly(item)) {
    await client.request("workspace/executeCommand", {
      command: item.command,
      arguments: item.arguments ?? [],
    });
    return { title: item.title, edits: [], commands: [item.command] };
  }

  let action = item as CodeAction;
  // codeAction/resolve fills in .edit if the server deferred it
  if (!action.edit) {
    const resolveProvider =
      typeof client.serverCapabilities.codeActionProvider === "object" &&
      (client.serverCapabilities.codeActionProvider as { resolveProvider?: boolean })?.resolveProvider;
    if (resolveProvider) {
      try {
        action = await client.request<CodeAction>("codeAction/resolve", action);
      } catch { /* resolve optional */ }
    }
  }

  const edits = action.edit
    ? await applyWorkspaceEdit(action.edit, cwd, uri => { void invalidateAcrossClients(uri); })
    : [];
  const commands: string[] = [];
  if (action.command) {
    await client.request("workspace/executeCommand", {
      command: action.command.command,
      arguments: action.command.arguments ?? [],
    });
    commands.push(action.command.command);
  }
  if (edits.length === 0 && commands.length === 0) return null;
  return { title: action.title, edits, commands };
}

// ─── Action enum ───────────────────────────────────────────────────────────

const ACTIONS = [
  "diagnostics",
  "hover",
  "definition",
  "type_definition",
  "implementation",
  "references",
  "symbols",
  "code_actions",
  "rename",
  "rename_file",
  "status",
  "reload",
  "capabilities",
  "request",
] as const;
type Action = (typeof ACTIONS)[number];

// ─── Extension entry point ─────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "lsp",
    label: "LSP",
    description:
      "Query a language server. Single `action` parameter selects the operation; " +
      "other parameters are optional depending on the action. Position-bearing " +
      "actions accept `line` (1-based) plus `symbol` (substring on that line, " +
      "optionally `name#N` for the Nth occurrence) which together resolve to a " +
      "column — no need to count characters. Apply-style actions (rename, " +
      "rename_file, code_actions) write to disk when `apply: true`. " +
      "Supported languages: " + SUPPORTED_LIST + ".",
    parameters: Type.Object({
      action: StringEnum(ACTIONS, {
        description:
          "Operation. " +
          "diagnostics: errors/warnings (file path or `*` for workspace). " +
          "hover/definition/type_definition/implementation/references: position queries. " +
          "symbols: documentSymbol when file given, workspace/symbol when omitted or `file: '*'`. " +
          "code_actions: list code actions at position; with apply+query, run the chosen one. " +
          "rename: textDocument/rename. " +
          "rename_file: workspace/willRenameFiles → fs.rename → didRenameFiles. " +
          "status / reload / capabilities: server admin. " +
          "request: send any LSP method via `query` + `payload`.",
      }),
      file: Type.Optional(Type.String({
        description: "Path to source file (absolute or relative). Use `*` for workspace scope on diagnostics/symbols/reload.",
      })),
      line: Type.Optional(Type.Integer({
        description: "1-based line number. Required for position-bearing actions.",
        minimum: 1,
      })),
      symbol: Type.Optional(Type.String({
        description: "Substring of the symbol on `line`. Resolves to column. Append `#N` to pick the Nth occurrence.",
      })),
      query: Type.Optional(Type.String({
        description: "Workspace-symbol search query, code-action selector (title substring or index), or LSP method name for action=request.",
      })),
      new_name: Type.Optional(Type.String({
        description: "Required for rename / rename_file. For rename_file: destination path.",
      })),
      apply: Type.Optional(Type.Boolean({
        description: "Apply edits to disk. Defaults: rename=true, rename_file=true, code_actions=false (preview).",
      })),
      timeout: Type.Optional(Type.Number({
        description: "Per-request timeout in seconds. Defaults to 15.",
        minimum: 1,
      })),
      payload: Type.Optional(Type.String({
        description: "JSON-encoded params for action=request. If omitted, params are derived from file/line/symbol.",
      })),
    }),
    async execute(_id, params, _signal, _onUpdate, _ctx) {
      const action = params.action as Action;
      const cwd = process.cwd();
      const timeoutMs = (params.timeout ?? 15) * 1000;

      // ── status ──────────────────────────────────────────────────────────
      if (action === "status") {
        const settled = await listSettledClients();
        if (settled.length === 0) {
          return {
            content: [{ type: "text", text: "No active language servers." }],
            details: { action, count: 0 },
          };
        }
        const lines = settled.map(({ client }) => {
          const ageMs = Date.now() - client.startedAt;
          const age = ageMs < 60_000 ? `${Math.round(ageMs / 1000)}s` : `${Math.round(ageMs / 60_000)}m`;
          return `  ${client.serverName} (${client.bin})\n    root: ${client.projectRoot}\n    uptime: ${age}`;
        });
        return {
          content: [{ type: "text", text: `Active language servers (${settled.length}):\n${lines.join("\n")}` }],
          details: { action, count: settled.length },
        };
      }

      // ── reload ──────────────────────────────────────────────────────────
      if (action === "reload") {
        if (!params.file || params.file === "*") {
          // Reload all
          const keys = Array.from(clients.keys());
          for (const key of keys) {
            try {
              const c = await clients.get(key);
              if (c) c.shutdown();
            } catch { /* ignore */ }
            dropClient(key);
          }
          return {
            content: [{ type: "text", text: `Reloaded ${keys.length} server(s).` }],
            details: { action, count: keys.length },
          };
        }
        const filepath = resolvePath(params.file);
        const spec = findServerForFile(filepath);
        if (!spec) {
          return {
            content: [{ type: "text", text: `No language server for ${params.file}. Supported: ${SUPPORTED_LIST}` }],
            details: { action, error: "unsupported_extension" },
          };
        }
        const root = await getProjectRoot(filepath);
        const key = clientKey(spec, root);
        const existing = await clients.get(key);
        if (existing) existing.shutdown();
        dropClient(key);
        return {
          content: [{ type: "text", text: `Reloaded ${spec.name} for ${root}.` }],
          details: { action, serverName: spec.name, projectRoot: root },
        };
      }

      // ── capabilities ────────────────────────────────────────────────────
      if (action === "capabilities") {
        if (!params.file) {
          return {
            content: [{ type: "text", text: "Error: file required for capabilities." }],
            details: { action, error: "missing_file" },
          };
        }
        const filepath = resolvePath(params.file);
        const spec = findServerForFile(filepath);
        if (!spec) {
          return {
            content: [{ type: "text", text: `No language server for ${params.file}. Supported: ${SUPPORTED_LIST}` }],
            details: { action, error: "unsupported_extension" },
          };
        }
        let client: LspClient;
        try {
          const root = await getProjectRoot(filepath);
          client = await getClient(spec, root);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: "Failed to start language server: " + msg }],
            details: { action, error: "lsp_init_failed" },
          };
        }
        const caps = client.serverCapabilities;
        return {
          content: [{ type: "text", text: JSON.stringify(caps, null, 2) }],
          details: { action, serverName: client.serverName },
        };
      }

      // ── rename_file ─────────────────────────────────────────────────────
      if (action === "rename_file") {
        if (!params.file || !params.new_name) {
          return {
            content: [{ type: "text", text: "Error: rename_file requires `file` (source) and `new_name` (destination)." }],
            details: { action, error: "missing_arg" },
          };
        }
        const source = resolvePath(params.file);
        const dest   = resolvePath(params.new_name);
        if (source === dest) {
          return {
            content: [{ type: "text", text: "Error: source and destination are identical." }],
            details: { action, error: "same_path" },
          };
        }
        let sourceStat: Awaited<ReturnType<typeof stat>>;
        try { sourceStat = await stat(source); } catch {
          return {
            content: [{ type: "text", text: `Error: source path does not exist: ${formatRelativePath(source, cwd)}` }],
            details: { action, error: "source_missing" },
          };
        }
        try {
          await stat(dest);
          return {
            content: [{ type: "text", text: `Error: destination already exists: ${formatRelativePath(dest, cwd)}` }],
            details: { action, error: "dest_exists" },
          };
        } catch { /* good */ }

        const enumerated = await enumerateRenamePairs(source, dest);
        if (enumerated.exceeded) {
          return {
            content: [{ type: "text", text: `Error: directory contains more than ${MAX_RENAME_PAIRS} files; rename in smaller batches.` }],
            details: { action, error: "too_many_files" },
          };
        }
        if (enumerated.pairs.length === 0) {
          return {
            content: [{ type: "text", text: "Error: no files to rename." }],
            details: { action, error: "empty" },
          };
        }

        // Pick a server based on the source file's extension. If the source is
        // a directory, use the first file's extension to pick.
        const sampleFile = sourceStat.isFile() ? source : uriToPath(enumerated.pairs[0].oldUri);
        const spec = findServerForFile(sampleFile);
        if (!spec) {
          return {
            content: [{ type: "text", text: `No language server matches ${formatRelativePath(sampleFile, cwd)}. Supported: ${SUPPORTED_LIST}` }],
            details: { action, error: "unsupported_extension" },
          };
        }
        let client: LspClient;
        try {
          const root = await getProjectRoot(sampleFile);
          client = await getClient(spec, root);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: "Failed to start language server: " + msg }],
            details: { action, error: "lsp_init_failed" },
          };
        }

        const shouldApply = params.apply !== false;
        let edit: WorkspaceEdit | null = null;
        try {
          edit = await client.request<WorkspaceEdit | null>(
            "workspace/willRenameFiles",
            { files: enumerated.pairs },
            timeoutMs,
          );
        } catch (err) {
          const e = err as Error & { code?: number };
          // -32601 = method not found. Servers without willRename simply skip edits.
          if (e.code !== -32601) {
            return {
              content: [{ type: "text", text: `willRenameFiles failed: ${e.message}` }],
              details: { action, error: "lsp_failure" },
            };
          }
        }

        const summary: string[] = [];
        const srcLabel = formatRelativePath(source, cwd);
        const dstLabel = formatRelativePath(dest, cwd);
        const fileCountLabel = sourceStat.isDirectory()
          ? `${enumerated.pairs.length} file${enumerated.pairs.length !== 1 ? "s" : ""} under ${srcLabel}`
          : srcLabel;

        if (!shouldApply) {
          summary.push(`Rename preview: ${fileCountLabel} → ${dstLabel}`);
          if (edit) {
            const preview = fmtWorkspaceEdit(edit, cwd);
            if (preview.length === 0) summary.push("  No LSP edits would be applied");
            else for (const line of preview) summary.push(`  ${line}`);
          } else {
            summary.push("  No LSP edits (server has no willRenameFiles)");
          }
          return {
            content: [{ type: "text", text: summary.join("\n") }],
            details: { action, serverName: client.serverName, applied: false },
          };
        }

        // Apply: LSP edits FIRST, then move the file(s), then notify with didRenameFiles
        if (edit) {
          try {
            const applied = await applyWorkspaceEdit(edit, cwd, uri => { void invalidateAcrossClients(uri); });
            for (const line of applied) summary.push(`  ${line}`);
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return {
              content: [{ type: "text", text: `Failed to apply willRename edits: ${msg}` }],
              details: { action, error: "apply_failed" },
            };
          }
        }
        try {
          await mkdir(dirname(dest), { recursive: true });
          await fsRename(source, dest);
          summary.push(`  Renamed ${srcLabel} → ${dstLabel}`);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: `Renamed LSP edits but fs.rename failed: ${msg}` }],
            details: { action, error: "fs_rename_failed" },
          };
        }
        try {
          client.notify("workspace/didRenameFiles", { files: enumerated.pairs });
        } catch { /* best-effort */ }
        for (const pair of enumerated.pairs) {
          await invalidateAcrossClients(pair.oldUri);
          await invalidateAcrossClients(pair.newUri);
        }
        return {
          content: [{ type: "text", text: `Applied rename:\n${summary.join("\n")}` }],
          details: { action, serverName: client.serverName, applied: true, pairs: enumerated.pairs.length },
        };
      }

      // ── request ─────────────────────────────────────────────────────────
      if (action === "request") {
        const method = params.query?.trim();
        if (!method) {
          return {
            content: [{ type: "text", text: "Error: action=request requires `query` to specify the LSP method name." }],
            details: { action, error: "missing_method" },
          };
        }
        let spec: ServerSpec | null = null;
        let filepath: string | null = null;
        if (params.file && params.file !== "*") {
          const fp = resolvePath(params.file);
          filepath = fp;
          spec = findServerForFile(fp);
          if (!spec) {
            return {
              content: [{ type: "text", text: `No language server for ${params.file}. Supported: ${SUPPORTED_LIST}` }],
              details: { action, error: "unsupported_extension" },
            };
          }
        } else {
          // pick the first active server
          const settled = await listSettledClients();
          if (settled.length === 0) {
            return {
              content: [{ type: "text", text: "No active language servers. Pass `file` to start one." }],
              details: { action, error: "no_servers" },
            };
          }
          spec = SERVER_MAP[Object.keys(SERVER_MAP).find(e => SERVER_MAP[e].name === settled[0].client.serverName)!];
        }

        let requestParams: unknown;
        if (params.payload !== undefined) {
          try { requestParams = JSON.parse(params.payload); } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return {
              content: [{ type: "text", text: `Error: invalid JSON in payload: ${msg}` }],
              details: { action, error: "bad_payload" },
            };
          }
        } else if (filepath) {
          const uri = fileToUri(filepath);
          if (params.line !== undefined) {
            const character = await resolveSymbolColumn(filepath, params.line, params.symbol);
            requestParams = { textDocument: { uri }, position: { line: params.line - 1, character } };
          } else {
            requestParams = { textDocument: { uri } };
          }
        } else {
          requestParams = {};
        }

        let client: LspClient;
        try {
          const root = filepath ? await getProjectRoot(filepath) : process.cwd();
          client = await getClient(spec!, root);
          if (filepath) await client.ensureOpen(filepath, spec!.languageId);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: "Failed to prepare LSP server: " + msg }],
            details: { action, error: "lsp_init_failed" },
          };
        }

        try {
          const result = await client.request<unknown>(method, requestParams, timeoutMs);
          const formatted = result === null || result === undefined
            ? "null"
            : typeof result === "string"
              ? result
              : JSON.stringify(result, null, 2);
          return {
            content: [{ type: "text", text: `${client.serverName} ← ${method}:\n${formatted}` }],
            details: { action, serverName: client.serverName, method },
          };
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: `LSP error on ${method}: ${msg}` }],
            details: { action, serverName: client.serverName, method, error: msg },
          };
        }
      }

      // ── All remaining actions require a file (or `*` for diagnostics/symbols) ──
      const file = params.file;
      const isWorkspace = file === "*";
      if (!file) {
        return {
          content: [{ type: "text", text: "Error: `file` is required (use `*` for workspace scope where supported)." }],
          details: { action, error: "missing_file" },
        };
      }

      // Workspace-symbols branch (no file, query-driven).
      if (action === "symbols" && isWorkspace) {
        const q = params.query?.trim();
        if (!q) {
          return {
            content: [{ type: "text", text: "Error: action=symbols with file=* requires `query`." }],
            details: { action, error: "missing_query" },
          };
        }
        // Query every active server in parallel; dedupe by location.
        const settled = await listSettledClients();
        if (settled.length === 0) {
          return {
            content: [{ type: "text", text: "No active language servers. Open a file via another action first." }],
            details: { action, error: "no_servers" },
          };
        }
        const all: Array<SymbolInfo & { _server?: string }> = [];
        await Promise.all(settled.map(async ({ client }) => {
          try {
            const res = await client.request<SymbolInfo[] | null>("workspace/symbol", { query: q }, timeoutMs);
            if (Array.isArray(res)) {
              for (const s of res) all.push({ ...s, _server: client.serverName });
            }
          } catch { /* server may not support workspace symbols */ }
        }));
        if (all.length === 0) {
          return {
            content: [{ type: "text", text: `No workspace symbols match "${q}".` }],
            details: { action, count: 0 },
          };
        }
        const lines = all.slice(0, 200).map(s => {
          const kind = fmtSymbolKind(s.kind);
          const loc = s.location ? fmtLocation(s.location, cwd) : "?";
          const container = s.containerName ? ` (${s.containerName})` : "";
          return `${kind} ${s.name}${container} @ ${loc}`;
        });
        const truncated = all.length > 200 ? `\n... ${all.length - 200} more` : "";
        return {
          content: [{ type: "text", text: `${all.length} symbol(s) matching "${q}":\n  ${lines.join("\n  ")}${truncated}` }],
          details: { action, count: all.length },
        };
      }

      const filepath = isWorkspace ? null : resolvePath(file);
      let spec: ServerSpec | null = null;
      let client: LspClient | null = null;
      if (filepath) {
        spec = findServerForFile(filepath);
        if (!spec) {
          const ext = filepath.split(".").pop() ?? "??";
          return {
            content: [{ type: "text", text: `No language server configured for .${ext}. Supported: ${SUPPORTED_LIST}` }],
            details: { action, error: "unsupported_extension" },
          };
        }
        try {
          const root = await getProjectRoot(filepath);
          client = await getClient(spec, root);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: "Failed to start language server: " + msg }],
            details: { action, error: "lsp_init_failed" },
          };
        }
      }

      // ── diagnostics ─────────────────────────────────────────────────────
      if (action === "diagnostics") {
        if (isWorkspace) {
          // No file given — return diagnostics from every currently open URI
          // across all settled clients. Useful after a code change.
          const settled = await listSettledClients();
          if (settled.length === 0) {
            return {
              content: [{ type: "text", text: "No active language servers." }],
              details: { action, count: 0 },
            };
          }
          const grouped: string[] = [];
          let total = 0;
          for (const { client: c } of settled) {
            for (const [uri, diags] of c.diagnostics) {
              if (diags.length === 0) continue;
              const fp = formatRelativePath(uriToPath(uri), cwd);
              for (const d of diags) {
                grouped.push(fmtDiagnostic(d, fp));
                total++;
              }
            }
          }
          if (total === 0) {
            return {
              content: [{ type: "text", text: "No diagnostics across open files in any server." }],
              details: { action, count: 0 },
            };
          }
          return {
            content: [{ type: "text", text: grouped.join("\n") }],
            details: { action, count: total },
          };
        }
        // Single-file diagnostics.
        const uri = pathToFileURL(filepath!).href;
        const waiter = client!.waitForNextDiagnostics(uri, DIAGNOSTICS_WAIT_MS);
        try {
          await client!.ensureOpen(filepath!, spec!.languageId);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: "Failed to open document: " + msg }],
            details: { action, error: "didopen_failed" },
          };
        }
        await waiter;
        const diags = client!.getDiagnostics(uri);
        if (diags.length === 0) {
          return {
            content: [{ type: "text", text: "No diagnostics — file is clean." }],
            details: { action, count: 0 },
          };
        }
        const relpath = formatRelativePath(filepath!, cwd);
        const formatted = diags.map(d => fmtDiagnostic(d, relpath)).join("\n");
        const errs  = diags.filter(d => d.severity === 1).length;
        const warns = diags.filter(d => d.severity === 2).length;
        const infos = diags.filter(d => d.severity === 3).length;
        const hints = diags.filter(d => d.severity === 4).length;
        const summary = `${diags.length} diagnostic(s): ${errs} error(s), ${warns} warning(s)` +
          (infos ? `, ${infos} info` : "") + (hints ? `, ${hints} hint(s)` : "") + ".";
        return {
          content: [{ type: "text", text: formatted + "\n\n" + summary }],
          details: { action, count: diags.length, errors: errs, warnings: warns, info: infos, hints },
        };
      }

      // ── Remaining actions all need an open file ─────────────────────────
      if (!filepath || !client || !spec) {
        return {
          content: [{ type: "text", text: `Error: action=${action} requires a concrete file path.` }],
          details: { action, error: "missing_file" },
        };
      }
      let uri: string;
      try {
        uri = await client.ensureOpen(filepath, spec.languageId);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "Failed to open document: " + msg }],
          details: { action, error: "didopen_failed" },
        };
      }

      // Position resolution for the positional actions.
      const positionalActions = new Set<Action>([
        "hover", "definition", "type_definition", "implementation",
        "references", "code_actions", "rename",
      ]);
      let position: Position | null = null;
      if (positionalActions.has(action)) {
        if (params.line === undefined) {
          return {
            content: [{ type: "text", text: `Error: \`line\` is required for action=${action}.` }],
            details: { action, error: "missing_line" },
          };
        }
        try {
          const character = await resolveSymbolColumn(filepath, params.line, params.symbol);
          position = { line: params.line - 1, character };
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: "text", text: `Symbol resolution failed: ${msg}` }],
            details: { action, error: "symbol_not_found" },
          };
        }
      }

      const relpath = formatRelativePath(filepath, cwd);

      try {
        switch (action) {
          case "hover": {
            const r = await client.request<{ contents?: unknown } | null>(
              "textDocument/hover",
              { textDocument: { uri }, position: position! },
              timeoutMs,
            );
            const text = r?.contents ? fmtHoverContents(r.contents) : "";
            return {
              content: [{ type: "text", text: text.trim()
                ? text
                : `No hover information at ${relpath}:${params.line}:${(position!.character + 1)}.` }],
              details: { action, serverName: client.serverName, file: relpath, line: params.line },
            };
          }
          case "definition":
          case "type_definition":
          case "implementation": {
            const method = action === "definition"
              ? "textDocument/definition"
              : action === "type_definition" ? "textDocument/typeDefinition" : "textDocument/implementation";
            const r = await client.request<unknown>(
              method,
              { textDocument: { uri }, position: position! },
              timeoutMs,
            );
            const locs = normalizeLocations(r);
            if (locs.length === 0) {
              return {
                content: [{ type: "text", text: `No ${action.replace("_", " ")} found at ${relpath}:${params.line}:${position!.character + 1}.` }],
                details: { action, serverName: client.serverName, count: 0 },
              };
            }
            const label = action === "definition" ? "Definitions"
              : action === "type_definition" ? "Type definitions" : "Implementations";
            return {
              content: [{ type: "text", text: `${label}:\n  ${locs.map(l => fmtLocation(l, cwd)).join("\n  ")}` }],
              details: { action, serverName: client.serverName, count: locs.length },
            };
          }
          case "references": {
            const r = await client.request<unknown>(
              "textDocument/references",
              { textDocument: { uri }, position: position!, context: { includeDeclaration: true } },
              timeoutMs,
            );
            const locs = normalizeLocations(r);
            if (locs.length === 0) {
              return {
                content: [{ type: "text", text: `No references at ${relpath}:${params.line}:${position!.character + 1}.` }],
                details: { action, serverName: client.serverName, count: 0 },
              };
            }
            return {
              content: [{ type: "text", text:
                `Found ${locs.length} references:\n  ${locs.map(l => fmtLocation(l, cwd)).join("\n  ")}` }],
              details: { action, serverName: client.serverName, count: locs.length },
            };
          }
          case "symbols": {
            const r = await client.request<unknown>(
              "textDocument/documentSymbol",
              { textDocument: { uri } },
              timeoutMs,
            );
            return {
              content: [{ type: "text", text: fmtDocumentSymbols(r, filepath) }],
              details: {
                action, serverName: client.serverName,
                count: Array.isArray(r) ? r.length : 0,
              },
            };
          }
          case "code_actions": {
            const cachedDiags = client.diagnostics.get(uri) ?? [];
            // Filter relevant diagnostics: those overlapping the position.
            const inRange = (d: LspDiagnostic) =>
              comparePosition(d.range.start, position!) <= 0 &&
              comparePosition(position!, d.range.end) <= 0;
            const ctxDiags = cachedDiags.filter(inRange);
            const onlyKinds = !params.apply && params.query ? [params.query] : undefined;
            const result = await client.request<CodeActionOrCommand[] | null>(
              "textDocument/codeAction",
              {
                textDocument: { uri },
                range: { start: position!, end: position! },
                context: {
                  diagnostics: ctxDiags.length > 0 ? ctxDiags : cachedDiags,
                  only: onlyKinds,
                  triggerKind: 1,
                },
              },
              timeoutMs,
            );
            if (!result || result.length === 0) {
              return {
                content: [{ type: "text", text: "No code actions available." }],
                details: { action, serverName: client.serverName, count: 0 },
              };
            }
            // Apply branch
            if (params.apply === true) {
              const sel = params.query?.trim();
              if (!sel) {
                return {
                  content: [{ type: "text", text: "Error: `query` is required when apply=true (action title substring or numeric index)." }],
                  details: { action, error: "missing_query" },
                };
              }
              const parsedIdx = /^\d+$/.test(sel) ? parseInt(sel, 10) : null;
              const chosen = result.find((a, i) =>
                (parsedIdx !== null && i === parsedIdx) ||
                a.title.toLowerCase().includes(sel.toLowerCase()),
              );
              if (!chosen) {
                const list = result.map((a, i) => `  ${fmtCodeAction(a, i)}`).join("\n");
                return {
                  content: [{ type: "text", text: `No code action matches "${sel}". Available:\n${list}` }],
                  details: { action, serverName: client.serverName, count: result.length },
                };
              }
              const applied = await applyCodeActionOrCommand(chosen, client, cwd);
              if (!applied) {
                return {
                  content: [{ type: "text", text: `Action "${chosen.title}" produced no edits and no commands.` }],
                  details: { action, serverName: client.serverName, applied: false },
                };
              }
              const lines: string[] = [];
              if (applied.edits.length > 0) {
                lines.push("  Workspace edit:");
                lines.push(...applied.edits.map(e => `    ${e}`));
              }
              if (applied.commands.length > 0) {
                lines.push("  Executed command(s):");
                lines.push(...applied.commands.map(c => `    ${c}`));
              }
              return {
                content: [{ type: "text", text: `Applied "${applied.title}":\n${lines.join("\n")}` }],
                details: { action, serverName: client.serverName, applied: true, title: applied.title },
              };
            }
            const lines = result.map((a, i) => `  ${fmtCodeAction(a, i)}`);
            return {
              content: [{ type: "text", text: `${result.length} code action(s):\n${lines.join("\n")}` }],
              details: { action, serverName: client.serverName, count: result.length },
            };
          }
          case "rename": {
            if (!params.new_name) {
              return {
                content: [{ type: "text", text: "Error: rename requires `new_name`." }],
                details: { action, error: "missing_new_name" },
              };
            }
            const result = await client.request<WorkspaceEdit | null>(
              "textDocument/rename",
              { textDocument: { uri }, position: position!, newName: params.new_name },
              timeoutMs,
            );
            if (!result) {
              return {
                content: [{ type: "text", text: "Rename returned no edits." }],
                details: { action, serverName: client.serverName, applied: false },
              };
            }
            const shouldApply = params.apply !== false;
            if (shouldApply) {
              const applied = await applyWorkspaceEdit(result, cwd, u => { void invalidateAcrossClients(u); });
              return {
                content: [{ type: "text", text: `Applied rename to "${params.new_name}":\n${applied.map(a => `  ${a}`).join("\n")}` }],
                details: { action, serverName: client.serverName, applied: true, edits: applied.length },
              };
            }
            const preview = fmtWorkspaceEdit(result, cwd);
            return {
              content: [{ type: "text", text: `Rename preview for "${params.new_name}":\n${preview.map(p => `  ${p}`).join("\n")}` }],
              details: { action, serverName: client.serverName, applied: false },
            };
          }
          default: {
            const _exhaustive: never = action as never;
            void _exhaustive;
            return {
              content: [{ type: "text", text: `Unknown action: ${action}` }],
              details: { error: "unknown_action" },
            };
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: `LSP error: ${msg}` }],
          details: { action, serverName: client.serverName, error: msg },
        };
      }
    },
  });
}
