/**
 * Pi extension: `lsp_query` + `lsp_diagnostics` tools.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/lsp-extension.ts and rebuild.
 *
 * Spawns a language server process and implements the LSP JSON-RPC 2.0
 * protocol to expose diagnostics, hover, go-to-definition, find-references,
 * document-symbols, and formatting as pi tools.
 *
 * Supported languages:
 *   Go       (.go)    → gopls
 *   TS/JS    (.ts .tsx .js .jsx) → typescript-language-server
 *   Rust     (.rs)    → rust-analyzer
 *   Nix      (.nix)   → nil
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawn } from "node:child_process";
import { Buffer } from "node:buffer";

// Absolute /nix/store paths — pinned at build time, no PATH dependency.
// Placeholders replaced by Nix at build time.
const GOLANG_LSP = "___GOLANG_LSP___";
const TS_LSP     = "___TS_LSP___";
const RUST_ANALYZER = "___RUST_ANALYZER___";
const NIX_LSP    = "___NIX_LSP___";

const DEFAULT_TIMEOUT_MS = 15000;

// File extension → server mapping
const SERVER_MAP: Record<string, { bin: string; args: string[] }> = {
  ".go":      { bin: GOLANG_LSP,        args: [] },
  ".ts":      { bin: TS_LSP,            args: ["stdio"] },
  ".tsx":     { bin: TS_LSP,            args: ["stdio"] },
  ".js":      { bin: TS_LSP,            args: ["stdio"] },
  ".jsx":     { bin: TS_LSP,            args: ["stdio"] },
  ".mts":     { bin: TS_LSP,            args: ["stdio"] },
  ".cts":     { bin: TS_LSP,            args: ["stdio"] },
  ".rs":      { bin: RUST_ANALYZER,     args: [] },
  ".nix":     { bin: NIX_LSP,           args: [] },
};

// ─── JSON-RPC Client ────────────────────────────────────────────────────────

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject: (err: Error) => void;
}

class LspClient {
  private proc: ReturnType<typeof spawn> | null = null;
  private pending = new Map<number, PendingRequest>();
  private nextId = 1;
  private ready = false;
  private stdoutBuf = "";

  async init(): Promise<void> {
    return new Promise((resolve, reject) => {
      // Seed with nil (Nix LSP) — its bin path is well-known.
      this.proc = spawn(NIX_LSP, []);

      this.proc.stdout.on("data", (chunk: Buffer) => {
        this.stdoutBuf += chunk.toString("utf8");
        this.drainStdout();
      });

      this.proc.stderr.on("data", (chunk: Buffer) => {
        console.error("[lsp stderr] " + chunk.toString("utf8").trim());
      });

      this.proc.on("error", (err) => {
        this.cleanup();
        reject(new Error("Language server process error: " + err.message));
      });

      this.proc.on("close", (code) => {
        this.cleanup();
        for (const [, p] of this.pending) {
          p.reject(new Error("Language server exited (code " + code + ")"));
        }
        this.pending.clear();
      });

      // Send initialize request
      const initReq = this.makeRequest("initialize", {
        processId: null,
        rootUri: null,
        capabilities: {},
        clientInfo: { name: "pi-lsp", version: "0.1" },
      });

      const handler = () => {
        const resp = this.parseResponse();
        if (resp && resp.id === initReq.id) {
          this.proc!.stdout.off("data", handler);
          this.ready = true;
          this.sendNotification("initialized", {});
          resolve();
        }
      };
      this.proc.stdout.on("data", handler);

      setTimeout(() => {
        this.proc!.stdout.off("data", handler);
        this.cleanup();
        reject(new Error("Language server initialization timed out"));
      }, 10000);
    });
  }

  async request<T>(method: string, params?: unknown): Promise<T> {
    if (!this.ready) throw new Error("LSP client not initialized");
    const body = this.makeRequest(method, params);
    return new Promise<T>((resolve, reject) => {
      const req = this.pending.get(body.id);
      if (req) req.reject(new Error("Request cancelled"));
      this.pending.set(body.id, { resolve: resolve as any, reject });
      this.proc!.stdin!.write(body);
      setTimeout(() => {
        const r = this.pending.get(body.id);
        if (r) {
          this.pending.delete(body.id);
          r.reject(new Error("LSP request timed out: " + method));
        }
      }, DEFAULT_TIMEOUT_MS);
    });
  }

  private sendNotification(method: string, params?: unknown): void {
    const body = this.mkBody(method, null, params);
    this.proc!.stdin!.write(body);
  }

  private makeRequest(method: string, params?: unknown): Buffer & { id: number } {
    const id = this.nextId++;
    const buf = this.mkBody(method, id, params) as Buffer & { id: number };
    (buf as any).id = id;
    return buf;
  }

  private mkBody(method: string, id: number | null, params?: unknown): Buffer {
    const json = JSON.stringify({
      jsonrpc: "2.0",
      method,
      params: params ?? {},
      id,
    });
    const header =
      "Content-Length: " +
      Buffer.byteLength(json, "utf8") +
      "\r\n\r\n";
    return Buffer.from(header + json, "utf8");
  }

  private drainStdout(): void {
    while (true) {
      const idx = this.stdoutBuf.indexOf("\r\n\r\n");
      if (idx === -1) break;
      const header = this.stdoutBuf.slice(0, idx);
      const clMatch = /Content-Length: (\d+)/i.exec(header);
      if (!clMatch) {
        this.stdoutBuf = this.stdoutBuf.slice(idx + 4);
        continue;
      }
      const contentLength = parseInt(clMatch[1], 10);
      const afterHeader = idx + 4;
      if (this.stdoutBuf.length < afterHeader + contentLength) break;
      const body = this.stdoutBuf.slice(afterHeader, afterHeader + contentLength);
      this.stdoutBuf = this.stdoutBuf.slice(afterHeader + contentLength);
      this.handleMessage(JSON.parse(body));
    }
  }

  private parseResponse(): { id: number | null; result?: unknown } | null {
    const idx = this.stdoutBuf.indexOf("\r\n\r\n");
    if (idx === -1) return null;
    const header = this.stdoutBuf.slice(0, idx);
    const clMatch = /Content-Length: (\d+)/i.exec(header);
    if (!clMatch) {
      this.stdoutBuf = this.stdoutBuf.slice(idx + 4);
      return null;
    }
    const contentLength = parseInt(clMatch[1], 10);
    const afterHeader = idx + 4;
    if (this.stdoutBuf.length < afterHeader + contentLength) return null;
    const body = this.stdoutBuf.slice(afterHeader, afterHeader + contentLength);
    this.stdoutBuf = this.stdoutBuf.slice(afterHeader + contentLength);
    try {
      return JSON.parse(body);
    } catch {
      return null;
    }
  }

  private handleMessage(
    msg: { id?: number | null; method?: string; result?: unknown; error?: unknown },
  ): void {
    if (
      msg.id !== null &&
      msg.id !== undefined &&
      msg.method === undefined
    ) {
      const req = this.pending.get(msg.id);
      if (req) {
        this.pending.delete(msg.id);
        if (msg.error) {
          const errMsg =
            typeof msg.error === "string"
              ? msg.error
              : typeof (msg.error as any).message === "string"
                ? (msg.error as any).message
                : JSON.stringify(msg.error);
          req.reject(new Error("LSP: " + errMsg));
        } else {
          req.resolve(msg.result);
        }
      }
    }
    // Notifications (no id, has method) are ignored
  }

  private cleanup(): void {
    if (this.proc) {
      this.proc.kill();
      this.proc = null;
    }
    this.pending.clear();
    this.ready = false;
    this.stdoutBuf = "";
  }
}

// ─── Utilities ──────────────────────────────────────────────────────────────

function uriFromFile(filepath: string): string {
  return "file://" + encodeURIComponent(filepath);
}

function formatDiagnostic(d: unknown): string {
  const obj: Record<string, unknown> =
    typeof d === "object" && d !== null ? d : {};
  const sev = ["", "Error", "Warning", "Info", "Hint"];
  const severity =
    obj.severity !== undefined
      ? sev[Math.min(Number(obj.severity), 4)] ?? "Unknown"
      : "Error";
  const source = obj.source ?? "";
  const code =
    obj.code !== undefined ? " [" + String(obj.code) + "]" : "";
  const range = obj.range;
  let pos = "";
  if (
    range &&
    typeof range === "object" &&
    (range as any).start
  ) {
    const r = range as Record<string, unknown>;
    const s = r.start as Record<string, unknown>;
    pos =
      " (line " +
      (Number(s.line) ?? 0) +
      ", col " +
      (Number(s.character) ?? 0 + 1) +
      ")";
  }
  return severity + pos + code + ": " + (obj.message ?? "");
}

function findServerForFile(
  filepath: string,
): { bin: string; ext: string } | null {
  const parts = filepath.split(".");
  if (parts.length < 2) return null;
  // Try multi-dot extension first (.tsx, .mts, .cts)
  if (parts.length >= 3) {
    const multi = "." + parts.slice(-2).join(".");
    if (SERVER_MAP[multi])
      return { bin: SERVER_MAP[multi].bin, ext: multi };
  }
  const simple = "." + parts[parts.length - 1];
  if (SERVER_MAP[simple]) return { bin: SERVER_MAP[simple].bin, ext: simple };
  return null;
}

// Single LSP client — shared across all tool calls, initialized lazily.
let lspClient: LspClient | null = null;

async function getLspClient(): Promise<LspClient> {
  if (!lspClient) {
    lspClient = new LspClient();
    await lspClient.init();
  }
  return lspClient;
}

// ─── Extension entry point ──────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  // ── lsp_query: hover, definition, references, symbols, format ──

  pi.registerTool({
    name: "lsp_query",
    label: "LSP Query",
    description:
      "Query a language server for hover info, go-to-definition, " +
      "find-references, document-symbols, or formatting. Supports " +
      "Go (.go), TypeScript/JS (.ts .tsx .js .jsx), Rust (.rs), and " +
      "Nix (.nix). Line and column are 1-based. Use lsp_diagnostics " +
      "for file-wide error checking.",
    parameters: Type.Object({
      tool: Type.Enum(
        {
          hover: "Show type info and documentation for a symbol.",
          definition: "Jump to the definition of a symbol.",
          references: "Find all references to a symbol.",
          document_symbols:
            "List all symbols (functions, types, etc.) in a file.",
          format:
            "Format the document according to the language server's formatting rules.",
        },
        { description: "Operation to perform." },
      ),
      filepath: Type.String({ description: "Absolute path to the source file." }),
      line: Type.Optional(
        Type.Integer({
          description:
            "Line number (1-based). Required for hover, definition, and references.",
        }),
      ),
      column: Type.Optional(
        Type.Integer({
          description:
            "Column number (1-based). Required for hover, definition, and references. Defaults to 1.",
        }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      const serverInfo = findServerForFile(params.filepath);
      if (!serverInfo) {
        const ext = params.filepath.split(".").pop() ?? "??";
        return {
          content: [
            {
              type: "text",
              text:
                "No language server configured for ." +
                ext +
                "'. Supported: .go (gopls), .ts/.tsx/.js/.jsx (typescript-language-server), .rs (rust-analyzer), .nix (nil).",
            },
          ],
          details: { error: "unsupported_extension" },
        };
      }

      const client = await getLspClient();
      const uri = uriFromFile(params.filepath);
      const line = params.line ?? 1;
      const column = params.column ?? 1;
      const pos = { line, character: column - 1 };

      try {
        // ── hover ────────────────────────────────────────────────
        if (params.tool === "hover") {
          const result = await client.request<{
            contents?: { kind?: string; value: string }[];
          }>("textDocument/hover", {
            textDocument: { uri },
            position: pos,
          });
          if (!result || !result.contents) {
            return {
              content: [
                {
                  type: "text",
                  text: "No hover information available at (" +
                    line +
                    ", " +
                    column +
                    ").",
                },
              ],
              details: {
                tool: params.tool,
                filepath: params.filepath,
              },
            };
          }
          const contents = result.contents;
          const textContent = contents.find(
            (c) => c.kind === "plaintext" || !c.kind,
          );
          const doc =
            textContent?.value ?? contents.map((c) => c.value).join("\n\n");
          return {
            content: [{ type: "text", text: doc }],
            details: {
              tool: params.tool,
              filepath: params.filepath,
              line,
              column,
            },
          };
        }

        // ── definition ───────────────────────────────────────────
        if (params.tool === "definition") {
          const result = await client.request<
            Array<{
              uri?: string;
              range?: {
                start: { line: number; character: number };
                end: { line: number; character: number };
              };
            }>
          >("textDocument/definition", {
            textDocument: { uri },
            position: pos,
          });
          if (!result || result.length === 0) {
            return {
              content: [
                {
                  type: "text",
                  text: "No definition found at (" +
                    line +
                    ", " +
                    column +
                    ").",
                },
              ],
              details: {
                tool: params.tool,
                filepath: params.filepath,
              },
            };
          }
          const lines = result.map((loc) => {
            const u = loc.uri
              ? decodeURIComponent(loc.uri)
              : "unknown";
            const r = loc.range;
            if (!r) return "  " + u;
            const s = r.start;
            return (
              "  " +
              u +
              " (line " +
              (s.line + 1) +
              ", col " +
              (s.character + 1) +
              ")"
            );
          });
          return {
            content: [
              {
                type: "text",
                text: "Definitions:\n" + lines.join("\n"),
              },
            ],
            details: {
              tool: params.tool,
              filepath: params.filepath,
              count: result.length,
            },
          };
        }

        // ── references ───────────────────────────────────────────
        if (params.tool === "references") {
          const result = await client.request<
            Array<{
              uri?: string;
              range?: { start: { line: number; character: number } };
            }>
          >("textDocument/references", {
            textDocument: { uri },
            position: pos,
            context: { includeDeclaration: true },
          });
          if (!result || result.length === 0) {
            return {
              content: [
                {
                  type: "text",
                  text: "No references found at (" +
                    line +
                    ", " +
                    column +
                    ").",
                },
              ],
              details: {
                tool: params.tool,
                filepath: params.filepath,
              },
            };
          }
          const lines = result.map((loc) => {
            const u = loc.uri
              ? decodeURIComponent(loc.uri)
              : "unknown";
            const r = loc.range;
            if (!r) return "  " + u;
            const s = r.start;
            return (
              "  " +
              u +
              " (line " +
              (s.line + 1) +
              ", col " +
              (s.character + 1) +
              ")"
            );
          });
          return {
            content: [
              {
                type: "text",
                text:
                  "Found " +
                  result.length +
                  " references:\n" +
                  lines.join("\n"),
              },
            ],
            details: {
              tool: params.tool,
              filepath: params.filepath,
              count: result.length,
            },
          };
        }

        // ── document_symbols ─────────────────────────────────────
        if (params.tool === "document_symbols") {
          const result = await client.request<
            Array<{
              name?: string;
              kind?: number;
              location?: {
                uri?: string;
                range?: { start: { line: number } };
              };
              children?: unknown[];
            }>
          >("textDocument/documentSymbols", { textDocument: { uri } });
          const items = Array.isArray(result) ? result : [];
          if (items.length === 0) {
            return {
              content: [
                { type: "text", text: "No symbols found in file." },
              ],
              details: {
                tool: params.tool,
                filepath: params.filepath,
              },
            };
          }
          const kindNames = [
            "",
            "File",
            "Module",
            "Namespace",
            "Package",
            "Class",
            "Method",
            "Property",
            "Field",
            "Constructor",
            "Enum",
            "Interface",
            "Function",
            "Variable",
            "Constant",
            "String",
            "Number",
            "Boolean",
            "Array",
            "Object",
            "Key",
            "Null",
            "EnumMember",
            "Struct",
            "Event",
            "Operator",
            "TypeParameter",
          ];
          function fmtSymbol(
            s: Record<string, unknown>,
            indent: number,
          ): string {
            const name = s.name ?? "?";
            const kind =
              kindNames[
                Math.min((s.kind as number) ?? 0, 27)
              ] ?? "Unknown";
            const loc = s.location as
              | Record<string, unknown>
              | undefined;
            const uriStr =
              loc?.uri && typeof loc.uri === "string"
                ? decodeURIComponent(loc.uri)
                : "";
            const r = loc?.range as
              | Record<string, unknown>
              | undefined;
            const ln =
              r?.start?.line !== undefined
                ? String(Number(r.start.line) + 1)
                : "";
            let lineStr = ln
              ? " (line " + ln + ")"
              : "";
            if (uriStr && uriStr !== params.filepath)
              lineStr = " (" + uriStr + lineStr + ")";
            const prefix =
              "  ".repeat(indent) +
              (indent > 0 ? "└ " : "") +
              name;
            const out = [prefix + " [" + kind + "]" + lineStr];
            if (
              s.children &&
              Array.isArray(s.children)
            ) {
              out.push(
                ...(s.children as Array<Record<string, unknown>>).map(
                  (c) => fmtSymbol(c, indent + 1),
                ),
              );
            }
            return out.join("\n");
          }
          const output = items
            .map((s) => fmtSymbol(s, 0))
            .join("\n\n");
          return {
            content: [{ type: "text", text: output }],
            details: {
              tool: params.tool,
              filepath: params.filepath,
              count: items.length,
            },
          };
        }

        // ── format ───────────────────────────────────────────────
        if (params.tool === "format") {
          const result = await client.request<
            Array<{
              textEdit?: {
                range: {
                  start: { line: number; character: number };
                  end: { line: number; character: number };
                };
                newText: string;
              };
            }>
          >("textDocument/formatting", {
            textDocument: { uri },
            options: { tabSize: 2, insertSpaces: true },
          });
          const edits = Array.isArray(result) ? result : [];
          if (edits.length === 0) {
            return {
              content: [
                {
                  type: "text",
                  text: "File is already properly formatted.",
                },
              ],
              details: {
                tool: params.tool,
                filepath: params.filepath,
              },
            };
          }
          let changes = "";
          for (const e of edits) {
            const te = e.textEdit;
            if (!te) continue;
            const { range, newText } = te;
            if (range && newText !== undefined) {
              const { start, end } = range;
              changes +=
                "Replace line " +
                (start.line + 1) +
                "-" +
                (end.line + 1) +
                ":\\n  → " +
                newText.replace(/\n/g, "\\n") +
                "\n";
            }
          }
          return {
            content: [
              {
                type: "text",
                text: "Formatting edits:\n" + changes,
              },
            ],
            details: {
              tool: params.tool,
              filepath: params.filepath,
              changes: edits.length,
            },
          };
        }
      } catch (err) {
        const msg =
          err instanceof Error ? err.message : String(err);
        return {
          content: [
            { type: "text", text: "LSP query failed: " + msg },
          ],
          details: {
            tool: params.tool,
            filepath: params.filepath,
            error: msg,
          },
        };
      }
    },
  });

  // ── lsp_diagnostics: file-wide errors/warnings ──────────────────────

  pi.registerTool({
    name: "lsp_diagnostics",
    label: "LSP Diagnostics",
    description:
      "Check a file for language-level errors, warnings, and hints. " +
      "Uses the appropriate language server (gopls, typescript-language-" +
      "server, rust-analyzer, or nil). Returns all diagnostics for the " +
      "file.",
    parameters: Type.Object({
      filepath: Type.String({
        description: "Absolute path to the source file.",
      }),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      const serverInfo = findServerForFile(params.filepath);
      if (!serverInfo) {
        const ext = params.filepath.split(".").pop() ?? "??";
        return {
          content: [
            {
              type: "text",
              text:
                "No language server configured for ." +
                ext +
                "'. Supported: .go (gopls), .ts/.tsx/.js/.jsx (typescript-language-server), .rs (rust-analyzer), .nix (nil).",
            },
          ],
          details: { error: "unsupported_extension" },
        };
      }

      const client = await getLspClient();
      const uri = uriFromFile(params.filepath);

      try {
        const result = await client.request<
          Array<{
            severity?: number;
            message: string;
            source?: string;
            code?: string | number;
            range: {
              start: { line: number; character: number };
              end: { line: number; character: number };
            };
          }>
        >("textDocument/diagnostics", { textDocument: { uri } });

        if (!result || result.length === 0) {
          return {
            content: [
              {
                type: "text",
                text: "No diagnostics found — file is clean!",
              },
            ],
            details: {
              tool: "lsp_diagnostics",
              filepath: params.filepath,
              count: 0,
            },
          };
        }

        const formatted = result.map(formatDiagnostic);
        const errorCount = result.filter((d) => d.severity === 1).length;
        const warnCount = result.filter(
          (d) => d.severity === 2,
        ).length;

        return {
          content: [
            {
              type: "text",
              text:
                formatted.join("\n") +
                "\n\n" +
                result.length +
                " diagnostic(s): " +
                errorCount +
                " error(s), " +
                warnCount +
                " warning(s).",
            },
          ],
          details: {
            tool: "lsp_diagnostics",
            filepath: params.filepath,
            count: result.length,
            errors: errorCount,
            warnings: warnCount,
          },
        };
      } catch (err) {
        const msg =
          err instanceof Error ? err.message : String(err);
        return {
          content: [
            { type: "text", text: "LSP diagnostics failed: " + msg },
          ],
          details: {
            tool: "lsp_diagnostics",
            filepath: params.filepath,
            error: msg,
          },
        };
      }
    },
  });
}
