/**
 * Pi extension: `lsp_query` + `lsp_diagnostics` tools.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/lsp-extension.ts and rebuild.
 *
 * Spawns one language server per (binary, project root) on first request
 * and reuses it for subsequent calls. Implements enough of LSP JSON-RPC 2.0
 * to expose diagnostics, hover, go-to-definition, find-references, document
 * symbols, and formatting as pi tools.
 *
 * Supported languages:
 *   Go      (.go)    → gopls
 *   TS/JS   (.ts .tsx .js .jsx .mts .cts) → typescript-language-server
 *   Rust    (.rs)    → rust-analyzer
 *   Nix     (.nix)   → nil
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { Buffer } from "node:buffer";
import { pathToFileURL, fileURLToPath } from "node:url";
import { readFile, stat } from "node:fs/promises";
import { resolve as resolvePath, dirname } from "node:path";

// Absolute /nix/store paths — replaced by Nix at build time.
const GOLANG_LSP    = "___GOLANG_LSP___";
const TS_LSP        = "___TS_LSP___";
const RUST_ANALYZER = "___RUST_ANALYZER___";
const NIX_LSP       = "___NIX_LSP___";

const REQUEST_TIMEOUT_MS  = 15000;
const INIT_TIMEOUT_MS     = 10000;
const DIAGNOSTICS_WAIT_MS = 2500;
const ROOT_MARKERS = ["go.mod", "Cargo.toml", "package.json", "tsconfig.json", "flake.nix", ".git"];

interface ServerSpec {
  bin: string;
  args: string[];
  languageId: string;
}

const SERVER_MAP: Record<string, ServerSpec> = {
  ".go":  { bin: GOLANG_LSP,    args: [],          languageId: "go" },
  ".ts":  { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript" },
  ".tsx": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescriptreact" },
  ".js":  { bin: TS_LSP,        args: ["--stdio"], languageId: "javascript" },
  ".jsx": { bin: TS_LSP,        args: ["--stdio"], languageId: "javascriptreact" },
  ".mts": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript" },
  ".cts": { bin: TS_LSP,        args: ["--stdio"], languageId: "typescript" },
  ".rs":  { bin: RUST_ANALYZER, args: [],          languageId: "rust" },
  ".nix": { bin: NIX_LSP,       args: [],          languageId: "nix" },
};

const SUPPORTED_LIST =
  ".go (gopls), .ts/.tsx/.js/.jsx/.mts/.cts (typescript-language-server), " +
  ".rs (rust-analyzer), .nix (nil)";

// ─── LSP types ──────────────────────────────────────────────────────────────

interface LspDiagnostic {
  severity?: number;
  message: string;
  source?: string;
  code?: string | number;
  range: {
    start: { line: number; character: number };
    end:   { line: number; character: number };
  };
}

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject:  (err: Error) => void;
  method:  string;
}

// ─── LSP client ─────────────────────────────────────────────────────────────

class LspClient {
  private proc: ChildProcessWithoutNullStreams;
  private pending = new Map<number, PendingRequest>();
  private nextId = 1;
  private stdoutBuf: Buffer = Buffer.alloc(0);
  private ready = false;
  private openDocs = new Map<string, { version: number; text: string; languageId: string }>();
  private diagnostics = new Map<string, LspDiagnostic[]>();
  private diagWaiters = new Map<string, () => void>();
  private fatalError: Error | null = null;
  readonly bin: string;
  private rootUri: string;
  onExit: (() => void) | null = null;

  constructor(spec: ServerSpec, projectRoot: string) {
    this.bin = spec.bin;
    this.rootUri = pathToFileURL(projectRoot + "/").href;

    this.proc = spawn(spec.bin, spec.args, {
      stdio: ["pipe", "pipe", "pipe"],
      cwd: projectRoot,
    });

    this.proc.stdout.on("data", (c: Buffer) => this.onData(c));
    this.proc.stderr.on("data", () => {
      // Servers can be chatty — discard.
    });
    this.proc.on("error", (err) => {
      this.fatalError = err;
      this.failAll(err);
      if (this.onExit) this.onExit();
    });
    this.proc.on("close", (code) => {
      const err = this.fatalError ?? new Error(
        "LSP server '" + spec.bin + "' exited (code " + code + ")",
      );
      this.fatalError = err;
      this.ready = false;
      this.failAll(err);
      if (this.onExit) this.onExit();
    });
    this.proc.stdin.on("error", () => { /* swallow; surfaced via 'close' */ });
  }

  private failAll(err: Error) {
    for (const [, p] of this.pending) {
      p.reject(new Error("LSP " + p.method + " failed: " + err.message));
    }
    this.pending.clear();
    for (const [, w] of this.diagWaiters) w();
    this.diagWaiters.clear();
  }

  async init(): Promise<void> {
    if (this.fatalError) throw this.fatalError;
    await this.sendRequest("initialize", {
      processId: typeof process !== "undefined" ? process.pid : null,
      rootUri: this.rootUri,
      workspaceFolders: [{ uri: this.rootUri, name: "root" }],
      capabilities: {
        textDocument: {
          publishDiagnostics: { relatedInformation: true },
          synchronization: {
            dynamicRegistration: false,
            willSave: false,
            didSave: false,
          },
          hover: { contentFormat: ["plaintext", "markdown"] },
          definition: { linkSupport: true },
          references: {},
          documentSymbol: { hierarchicalDocumentSymbolSupport: true },
          formatting: {},
        },
        workspace: {
          workspaceFolders: true,
          configuration: true,
        },
      },
      clientInfo: { name: "pi-lsp", version: "0.2" },
    }, INIT_TIMEOUT_MS);
    this.ready = true;
    this.sendNotification("initialized", {});
  }

  // ── Public API ────────────────────────────────────────────────────────────

  request<T>(method: string, params: unknown): Promise<T> {
    if (!this.ready) {
      return Promise.reject(new Error("LSP client not initialized"));
    }
    return this.sendRequest<T>(method, params, REQUEST_TIMEOUT_MS);
  }

  async ensureOpen(filepath: string, languageId: string): Promise<string> {
    const uri = pathToFileURL(filepath).href;
    let text: string;
    try {
      text = await readFile(filepath, "utf8");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error("cannot read " + filepath + ": " + msg);
    }
    const existing = this.openDocs.get(uri);
    if (existing) {
      if (existing.text === text) return uri;
      const newVersion = existing.version + 1;
      this.sendNotification("textDocument/didChange", {
        textDocument: { uri, version: newVersion },
        contentChanges: [{ text }],
      });
      this.openDocs.set(uri, { version: newVersion, text, languageId: existing.languageId });
    } else {
      this.sendNotification("textDocument/didOpen", {
        textDocument: { uri, languageId, version: 1, text },
      });
      this.openDocs.set(uri, { version: 1, text, languageId });
    }
    return uri;
  }

  getDiagnostics(uri: string): LspDiagnostic[] {
    return this.diagnostics.get(uri) ?? [];
  }

  /**
   * Resolves on the next `publishDiagnostics` for `uri`, or after
   * `timeoutMs`. Must be set up *before* triggering didOpen/didChange.
   */
  waitForNextDiagnostics(uri: string, timeoutMs: number): Promise<void> {
    return new Promise<void>((resolve) => {
      let done = false;
      const finish = () => {
        if (done) return;
        done = true;
        if (this.diagWaiters.get(uri) === finish) this.diagWaiters.delete(uri);
        resolve();
      };
      this.diagWaiters.set(uri, finish);
      setTimeout(finish, timeoutMs);
    });
  }

  shutdown() {
    try { this.proc.kill(); } catch { /* ignore */ }
  }

  // ── Internals ─────────────────────────────────────────────────────────────

  private sendRequest<T>(method: string, params: unknown, timeoutMs: number): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      if (this.fatalError) { reject(this.fatalError); return; }
      const id = this.nextId++;
      const timer = setTimeout(() => {
        if (this.pending.delete(id)) {
          reject(new Error("LSP " + method + " timed out after " + timeoutMs + "ms"));
        }
      }, timeoutMs);
      this.pending.set(id, {
        resolve: (v) => { clearTimeout(timer); resolve(v as T); },
        reject:  (e) => { clearTimeout(timer); reject(e); },
        method,
      });
      this.write({ jsonrpc: "2.0", method, params: params ?? {}, id });
    });
  }

  private onData(chunk: Buffer) {
    this.stdoutBuf = Buffer.concat([this.stdoutBuf, chunk]);
    while (true) {
      const headerEnd = this.stdoutBuf.indexOf("\r\n\r\n");
      if (headerEnd === -1) return;
      const header = this.stdoutBuf.slice(0, headerEnd).toString("utf8");
      const m = /Content-Length:\s*(\d+)/i.exec(header);
      if (!m) {
        // Malformed — drop the header and resync
        this.stdoutBuf = this.stdoutBuf.slice(headerEnd + 4);
        continue;
      }
      const len = parseInt(m[1], 10);
      const bodyStart = headerEnd + 4;
      if (this.stdoutBuf.length < bodyStart + len) return;
      const body = this.stdoutBuf.slice(bodyStart, bodyStart + len).toString("utf8");
      this.stdoutBuf = this.stdoutBuf.slice(bodyStart + len);
      try {
        this.handleMessage(JSON.parse(body));
      } catch {
        // Ignore malformed JSON
      }
    }
  }

  private handleMessage(msg: any) {
    // Response to a request we sent
    if (
      (typeof msg.id === "number" || typeof msg.id === "string") &&
      msg.method === undefined
    ) {
      const id = typeof msg.id === "number" ? msg.id : parseInt(msg.id as string, 10);
      const req = this.pending.get(id);
      if (!req) return;
      this.pending.delete(id);
      if (msg.error) {
        const m =
          typeof msg.error === "object" && msg.error && typeof msg.error.message === "string"
            ? msg.error.message
            : JSON.stringify(msg.error);
        req.reject(new Error("LSP " + req.method + ": " + m));
      } else {
        req.resolve(msg.result);
      }
      return;
    }

    if (typeof msg.method !== "string") return;

    // Server → client notification
    if (msg.method === "textDocument/publishDiagnostics" && msg.params) {
      const uri = msg.params.uri;
      if (typeof uri !== "string") return;
      const diags = Array.isArray(msg.params.diagnostics)
        ? (msg.params.diagnostics as LspDiagnostic[])
        : [];
      this.diagnostics.set(uri, diags);
      const w = this.diagWaiters.get(uri);
      if (w) w();
      return;
    }

    // Server → client request (must respond)
    if (msg.id !== undefined && msg.id !== null) {
      let result: unknown = null;
      if (msg.method === "workspace/configuration") {
        const n = Array.isArray(msg.params?.items) ? msg.params.items.length : 0;
        result = new Array(n).fill(null);
      } else if (msg.method === "workspace/workspaceFolders") {
        result = [{ uri: this.rootUri, name: "root" }];
      }
      // For client/registerCapability, window/workDoneProgress/create, etc.
      // a `null` result is a valid ack.
      this.respond(msg.id as number | string, result);
    }
    // Pure notifications (window/logMessage, $/progress) are ignored.
  }

  private respond(id: number | string, result: unknown) {
    this.write({ jsonrpc: "2.0", id, result });
  }

  private sendNotification(method: string, params: unknown) {
    this.write({ jsonrpc: "2.0", method, params: params ?? {} });
  }

  private write(payload: unknown) {
    if (this.fatalError) return;
    const json = JSON.stringify(payload);
    const header = "Content-Length: " + Buffer.byteLength(json, "utf8") + "\r\n\r\n";
    try {
      this.proc.stdin.write(header + json);
    } catch (err) {
      this.fatalError = err instanceof Error ? err : new Error(String(err));
    }
  }
}

// ─── Client pool ────────────────────────────────────────────────────────────

const clients = new Map<string, Promise<LspClient>>();

async function getClient(spec: ServerSpec, projectRoot: string): Promise<LspClient> {
  const key = spec.bin + "@" + projectRoot;
  let existing = clients.get(key);
  if (existing) return existing;

  const created = (async () => {
    const c = new LspClient(spec, projectRoot);
    c.onExit = () => {
      // Evict on exit so the next request respawns a fresh client.
      if (clients.get(key) === created) clients.delete(key);
    };
    try {
      await c.init();
    } catch (err) {
      clients.delete(key);
      c.shutdown();
      throw err;
    }
    return c;
  })();
  clients.set(key, created);
  return created;
}

// ─── Project root discovery ─────────────────────────────────────────────────

const projectRootCache = new Map<string, string>();

async function findProjectRoot(filepath: string): Promise<string> {
  let dir = dirname(resolvePath(filepath));
  for (let i = 0; i < 32; i++) {
    for (const m of ROOT_MARKERS) {
      try {
        await stat(dir + "/" + m);
        return dir;
      } catch { /* not found */ }
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return dirname(resolvePath(filepath));
}

async function getProjectRoot(filepath: string): Promise<string> {
  const abs = resolvePath(filepath);
  let root = projectRootCache.get(abs);
  if (!root) {
    root = await findProjectRoot(abs);
    projectRootCache.set(abs, root);
  }
  return root;
}

// ─── Lookups & formatters ───────────────────────────────────────────────────

function findServerForFile(filepath: string): ServerSpec | null {
  const lower = filepath.toLowerCase();
  // Multi-character extensions first
  for (const ext of [".tsx", ".jsx", ".mts", ".cts"]) {
    if (lower.endsWith(ext)) return SERVER_MAP[ext];
  }
  const dotIdx = lower.lastIndexOf(".");
  if (dotIdx === -1) return null;
  return SERVER_MAP[lower.slice(dotIdx)] ?? null;
}

function uriToPath(uri: string): string {
  try { return fileURLToPath(uri); } catch { return uri; }
}

const SEVERITY_NAMES = ["", "Error", "Warning", "Info", "Hint"];

function fmtDiagnostic(d: LspDiagnostic, filepath: string): string {
  const sev = d.severity !== undefined
    ? (SEVERITY_NAMES[Math.min(d.severity, 4)] ?? "Unknown")
    : "Error";
  const line = (d.range?.start?.line ?? 0) + 1;
  const col  = (d.range?.start?.character ?? 0) + 1;
  const src  = d.source ? " [" + d.source + "]" : "";
  const code = d.code !== undefined ? " (" + String(d.code) + ")" : "";
  return sev + " " + filepath + ":" + line + ":" + col + src + code + " — " + d.message;
}

function fmtPosition(line0: number, char0: number): string {
  return "line " + (line0 + 1) + ", col " + (char0 + 1);
}

interface Location {
  uri: string;
  range: {
    start: { line: number; character: number };
    end:   { line: number; character: number };
  };
}

function normalizeLocations(result: unknown): Location[] {
  if (!result) return [];
  const arr = Array.isArray(result) ? result : [result];
  const out: Location[] = [];
  for (const item of arr) {
    if (!item || typeof item !== "object") continue;
    const obj = item as any;
    // LocationLink → Location
    if (obj.targetUri && obj.targetRange) {
      out.push({ uri: obj.targetUri, range: obj.targetRange });
    } else if (obj.uri && obj.range) {
      out.push({ uri: obj.uri, range: obj.range });
    }
  }
  return out;
}

function fmtLocation(loc: Location): string {
  return uriToPath(loc.uri) +
    " (" + fmtPosition(loc.range.start.line, loc.range.start.character) + ")";
}

function fmtHoverContents(contents: unknown): string {
  if (!contents) return "";
  if (typeof contents === "string") return contents;
  if (Array.isArray(contents)) {
    return contents.map(fmtHoverContents).filter(Boolean).join("\n\n");
  }
  if (typeof contents === "object") {
    const c = contents as any;
    if (typeof c.value === "string") {
      // MarkedString: { language, value }
      if (typeof c.language === "string") {
        return "```" + c.language + "\n" + c.value + "\n```";
      }
      // MarkupContent: { kind, value }
      return c.value;
    }
  }
  return "";
}

const SYMBOL_KIND_NAMES = [
  "", "File", "Module", "Namespace", "Package", "Class", "Method", "Property",
  "Field", "Constructor", "Enum", "Interface", "Function", "Variable", "Constant",
  "String", "Number", "Boolean", "Array", "Object", "Key", "Null", "EnumMember",
  "Struct", "Event", "Operator", "TypeParameter",
];

function fmtSymbolKind(kind: unknown): string {
  const n = typeof kind === "number" ? kind : 0;
  return SYMBOL_KIND_NAMES[n] ?? "Unknown";
}

// Handles both DocumentSymbol[] (hierarchical) and SymbolInformation[] (flat)
function fmtDocumentSymbols(result: unknown, filepath: string): string {
  if (!Array.isArray(result) || result.length === 0) {
    return "No symbols found in file.";
  }
  const lines: string[] = [];
  const visit = (items: any[], depth: number) => {
    for (const s of items) {
      if (!s || typeof s !== "object") continue;
      const indent = "  ".repeat(depth);
      const arrow  = depth > 0 ? "└ " : "";
      const name   = s.name ?? "?";
      const kind   = fmtSymbolKind(s.kind);
      const range  = s.range ?? s.location?.range;
      const lineStr = range?.start?.line !== undefined
        ? " (line " + (range.start.line + 1) + ")"
        : "";
      let suffix = lineStr;
      // SymbolInformation can reference another file
      const uri = s.location?.uri as string | undefined;
      if (uri) {
        const p = uriToPath(uri);
        if (p !== filepath) suffix = " [" + p + "]" + lineStr;
      }
      lines.push(indent + arrow + name + " [" + kind + "]" + suffix);
      if (Array.isArray(s.children)) visit(s.children, depth + 1);
    }
  };
  visit(result, 0);
  return lines.join("\n");
}

// ─── Extension entry point ──────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "lsp_query",
    label: "LSP Query",
    description:
      "Query a language server for hover info, go-to-definition, " +
      "find-references, document-symbols, or formatting. Supports " +
      "Go (.go), TypeScript/JS (.ts .tsx .js .jsx .mts .cts), Rust (.rs), " +
      "and Nix (.nix). Line and column are 1-based.",
    parameters: Type.Object({
      tool: StringEnum(
        ["hover", "definition", "references", "document_symbols", "format"] as const,
        {
          description:
            "Operation: hover (type info), definition (jump to def), " +
            "references (find usages), document_symbols (list file symbols), " +
            "format (formatting edits).",
        },
      ),
      filepath: Type.String({ description: "Path to the source file (absolute or relative)." }),
      line: Type.Optional(Type.Integer({
        description:
          "Line number (1-based). Required for hover, definition, references. " +
          "Ignored for document_symbols and format.",
        minimum: 1,
      })),
      column: Type.Optional(Type.Integer({
        description:
          "Column number (1-based). Used with line for position-based queries " +
          "(defaults to 1). Ignored for document_symbols and format.",
        minimum: 1,
      })),
    }),
    async execute(_id, params, _signal, _onUpdate, _ctx) {
      const filepath = resolvePath(params.filepath);
      const spec = findServerForFile(filepath);
      if (!spec) {
        const ext = filepath.split(".").pop() ?? "??";
        return {
          content: [{ type: "text", text:
            "No language server configured for ." + ext +
            ". Supported: " + SUPPORTED_LIST }],
          details: { error: "unsupported_extension", filepath },
        };
      }

      const isPositional =
        params.tool === "hover" ||
        params.tool === "definition" ||
        params.tool === "references";
      if (isPositional && params.line === undefined) {
        return {
          content: [{ type: "text", text:
            "Error: 'line' is required for " + params.tool +
            ". Pass a 1-based line number." }],
          details: { error: "missing_line", tool: params.tool },
        };
      }

      let client: LspClient;
      try {
        const root = await getProjectRoot(filepath);
        client = await getClient(spec, root);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "Failed to start language server: " + msg }],
          details: { error: "lsp_init_failed", message: msg },
        };
      }

      let uri: string;
      try {
        uri = await client.ensureOpen(filepath, spec.languageId);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "Failed to open document: " + msg }],
          details: { error: "didopen_failed", message: msg },
        };
      }

      const line0 = (params.line ?? 1) - 1;
      const char0 = (params.column ?? 1) - 1;
      const position = { line: line0, character: char0 };

      try {
        switch (params.tool) {
          case "hover": {
            const r = await client.request<any>("textDocument/hover", {
              textDocument: { uri },
              position,
            });
            const text = r?.contents ? fmtHoverContents(r.contents) : "";
            return {
              content: [{ type: "text", text: text.trim()
                ? text
                : "No hover information at " + fmtPosition(line0, char0) + "." }],
              details: {
                tool: "hover", filepath,
                line: params.line, column: params.column ?? 1,
              },
            };
          }
          case "definition": {
            const r = await client.request<unknown>("textDocument/definition", {
              textDocument: { uri },
              position,
            });
            const locs = normalizeLocations(r);
            if (locs.length === 0) {
              return {
                content: [{ type: "text", text:
                  "No definition found at " + fmtPosition(line0, char0) + "." }],
                details: { tool: "definition", filepath, count: 0 },
              };
            }
            return {
              content: [{ type: "text", text:
                "Definitions:\n  " + locs.map(fmtLocation).join("\n  ") }],
              details: { tool: "definition", filepath, count: locs.length },
            };
          }
          case "references": {
            const r = await client.request<unknown>("textDocument/references", {
              textDocument: { uri },
              position,
              context: { includeDeclaration: true },
            });
            const locs = normalizeLocations(r);
            if (locs.length === 0) {
              return {
                content: [{ type: "text", text:
                  "No references found at " + fmtPosition(line0, char0) + "." }],
                details: { tool: "references", filepath, count: 0 },
              };
            }
            return {
              content: [{ type: "text", text:
                "Found " + locs.length + " references:\n  " +
                locs.map(fmtLocation).join("\n  ") }],
              details: { tool: "references", filepath, count: locs.length },
            };
          }
          case "document_symbols": {
            const r = await client.request<unknown>("textDocument/documentSymbol", {
              textDocument: { uri },
            });
            return {
              content: [{ type: "text", text: fmtDocumentSymbols(r, filepath) }],
              details: {
                tool: "document_symbols", filepath,
                count: Array.isArray(r) ? r.length : 0,
              },
            };
          }
          case "format": {
            const r = await client.request<Array<{
              range: { start: { line: number; character: number }; end: { line: number; character: number } };
              newText: string;
            }>>("textDocument/formatting", {
              textDocument: { uri },
              options: { tabSize: 2, insertSpaces: true },
            });
            const edits = Array.isArray(r) ? r : [];
            if (edits.length === 0) {
              return {
                content: [{ type: "text", text: "File is already properly formatted." }],
                details: { tool: "format", filepath, edits: 0 },
              };
            }
            const lines = edits.map((e) => {
              const s = e.range.start, eP = e.range.end;
              const preview = e.newText.length > 200
                ? e.newText.slice(0, 200) + "…"
                : e.newText;
              return "  " + (s.line + 1) + ":" + (s.character + 1) +
                " → " + (eP.line + 1) + ":" + (eP.character + 1) +
                "  newText=" + JSON.stringify(preview);
            });
            return {
              content: [{ type: "text", text:
                "Formatting edits (" + edits.length + "):\n" + lines.join("\n") }],
              details: { tool: "format", filepath, edits: edits.length },
            };
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "LSP query failed: " + msg }],
          details: { tool: params.tool, filepath, error: msg },
        };
      }
      // Unreachable — switch is exhaustive
      return {
        content: [{ type: "text", text: "Unknown tool: " + String((params as any).tool) }],
        details: { error: "unknown_tool" },
      };
    },
  });

  pi.registerTool({
    name: "lsp_diagnostics",
    label: "LSP Diagnostics",
    description:
      "Check a file for language-level errors, warnings, and hints. " +
      "Uses the appropriate language server (gopls, typescript-language-server, " +
      "rust-analyzer, or nil). Returns all diagnostics for the file.",
    parameters: Type.Object({
      filepath: Type.String({ description: "Path to the source file (absolute or relative)." }),
    }),
    async execute(_id, params, _signal, _onUpdate, _ctx) {
      const filepath = resolvePath(params.filepath);
      const spec = findServerForFile(filepath);
      if (!spec) {
        const ext = filepath.split(".").pop() ?? "??";
        return {
          content: [{ type: "text", text:
            "No language server configured for ." + ext +
            ". Supported: " + SUPPORTED_LIST }],
          details: { error: "unsupported_extension", filepath },
        };
      }

      let client: LspClient;
      try {
        const root = await getProjectRoot(filepath);
        client = await getClient(spec, root);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "Failed to start language server: " + msg }],
          details: { error: "lsp_init_failed", message: msg },
        };
      }

      // Set up the diagnostics waiter *before* triggering didOpen/didChange,
      // so we don't race against the publishDiagnostics notification.
      const uri = pathToFileURL(filepath).href;
      const waiter = client.waitForNextDiagnostics(uri, DIAGNOSTICS_WAIT_MS);

      try {
        await client.ensureOpen(filepath, spec.languageId);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: "Failed to open document: " + msg }],
          details: { error: "didopen_failed", message: msg },
        };
      }

      await waiter;
      const diags = client.getDiagnostics(uri);

      if (diags.length === 0) {
        return {
          content: [{ type: "text", text: "No diagnostics — file is clean." }],
          details: { tool: "lsp_diagnostics", filepath, count: 0 },
        };
      }

      const errorCount = diags.filter((d) => d.severity === 1).length;
      const warnCount  = diags.filter((d) => d.severity === 2).length;
      const infoCount  = diags.filter((d) => d.severity === 3).length;
      const hintCount  = diags.filter((d) => d.severity === 4).length;

      const formatted = diags.map((d) => fmtDiagnostic(d, filepath)).join("\n");
      const summary =
        diags.length + " diagnostic(s): " +
        errorCount + " error(s), " + warnCount + " warning(s)" +
        (infoCount ? ", " + infoCount + " info" : "") +
        (hintCount ? ", " + hintCount + " hint(s)" : "") + ".";

      return {
        content: [{ type: "text", text: formatted + "\n\n" + summary }],
        details: {
          tool: "lsp_diagnostics", filepath,
          count: diags.length,
          errors: errorCount, warnings: warnCount,
          info: infoCount, hints: hintCount,
        },
      };
    },
  });
}
