{
  config,
  pkgs,
  lib,
  ...
}:

let
  # Pi extension: `web_search` tool backed by ddgr (DuckDuckGo CLI).
  #
  # The TypeScript source is materialized into the Nix store with the
  # absolute path to ddgr baked in, then symlinked into
  # ~/.pi/agent/extensions/ where pi auto-discovers single-file extensions.
  #
  # Nix-string escaping rules in effect:
  #   ${...}        Nix interpolation
  #   ''${...}      literal "${...}" in the output (we do not use any)
  #   '''           literal "''"     in the output (we do not use any)
  webSearchExtension = pkgs.writeText "web-search.ts" ''
    /**
     * Pi extension: `web_search` tool backed by ddgr (DuckDuckGo CLI).
     *
     * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
     * edit the Nix source and rebuild.
     */
    import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
    import { Type } from "typebox";
    import { execFile } from "node:child_process";
    import { promisify } from "node:util";

    const execFileP = promisify(execFile);

    // Absolute /nix/store path; pinned at build time, no PATH dependency.
    const DDGR = "${pkgs.ddgr}/bin/ddgr";

    interface DdgrResult {
      title?: string;
      url?: string;
      abstract?: string;
    }

    export default function (pi: ExtensionAPI) {
      pi.registerTool({
        name: "web_search",
        label: "Web Search",
        description:
          "Search the web via DuckDuckGo using ddgr. Returns a numbered list " +
          "of results with title, URL, and abstract. Use for finding " +
          "documentation, blog posts, GitHub repos, or general lookups. " +
          "Follow up with `read` (URL) or `bash` curl to fetch specific pages.",
        parameters: Type.Object({
          query: Type.String({ description: "Search query (plain text)." }),
          num: Type.Optional(
            Type.Integer({
              description: "Number of results to return (default 5, max 25).",
              minimum: 1,
              maximum: 25,
            }),
          ),
        }),
        async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
          const num = params.num ?? 5;

          let stdout: string;
          try {
            const r = await execFileP(
              DDGR,
              ["--json", "--num", String(num), "--noprompt", params.query],
              { signal, maxBuffer: 4 * 1024 * 1024 },
            );
            stdout = r.stdout;
          } catch (err: unknown) {
            const msg = err instanceof Error ? err.message : String(err);
            return {
              content: [{ type: "text", text: "ddgr failed: " + msg }],
              details: { error: "exec_failed", message: msg },
            };
          }

          let results: DdgrResult[];
          try {
            results = JSON.parse(stdout);
          } catch {
            return {
              content: [
                {
                  type: "text",
                  text:
                    "ddgr did not return JSON (possibly rate-limited or CAPTCHA).\n" +
                    "Raw output (truncated):\n" +
                    stdout.slice(0, 2000),
                },
              ],
              details: { error: "bad_json" },
            };
          }

          if (!Array.isArray(results) || results.length === 0) {
            return {
              content: [{ type: "text", text: "No results for: " + params.query }],
              details: { query: params.query, count: 0 },
            };
          }

          const text = results
            .map((r, i) => {
              const title = r.title ?? "(no title)";
              const url = r.url ?? "";
              const abstract = (r.abstract ?? "").trim();
              return (
                (i + 1) + ". " + title + "\n   " + url +
                (abstract ? "\n   " + abstract : "")
              );
            })
            .join("\n\n");

          return {
            content: [{ type: "text", text }],
            details: {
              query: params.query,
              count: results.length,
              results,
            },
          };
        },
      });
    }
  '';
in
{
  # Pi auto-discovers single-file extensions in this directory.
  # See: ~/.npm-global/lib/node_modules/@earendil-works/pi-coding-agent/README.md
  # (Customization → Extensions).
  home.file.".pi/agent/extensions/web-search.ts".source = webSearchExtension;
}
