{
  config,
  lib,
  pkgs,
  ...
}:

let
  # Single-binary Rust toolbox of high-performance, context-aware primitives
  # invoked by pi extensions. Subcommands: hash, grep, summary, html2md,
  # ast-grep, ast-edit. Vendored from oh-my-pi (MIT, Can Boluk) under
  # home/cli/pi-rs/ and evolved independently. Builds natively on
  # x86_64-linux, aarch64-linux, and aarch64-darwin.
  piRs = pkgs.callPackage ../../home/cli/pi-rs { };

  # Directory-style pi extension that forks oh-my-pi's 78 site-specific
  # web_fetch handlers (arxiv, github, npm, pypi, crates.io, docs.rs, mdn,
  # stackoverflow, hackernews, wikipedia, …). Builds a deterministic
  # node_modules tree (linkedom) via buildNpmPackage. The compat layer
  # under ./pi-extensions/web-fetch/compat/ remaps the omp internal
  # surface onto local primitives, including spawning `pi-rs html2md` in
  # place of bundling turndown.
  webFetchOmpExtension = pkgs.callPackage ./pi-extensions/web-fetch { };

  # Directory-style pi extension that forks oh-my-pi's multi-provider
  # web_search chain. Active providers: Anthropic (api-key, restored
  # locally) + Tavily, Perplexity, Brave, Jina, Kimi, Z.AI, Kagi,
  # Synthetic, SearXNG. Gemini, Codex, Exa-MCP, and Parallel remain
  # disabled — they need pi-ai OAuth vendoring.
  webSearchOmpExtension = pkgs.callPackage ./pi-extensions/web-search { };

  # NOTE: The legacy single-file `web_search` (ddgr-backed) and
  # `web_fetch` (trafilatura-backed) extensions used to live here. They
  # were retired once the directory-style forks of oh-my-pi's versions
  # took over those canonical names: ddgr was reliably CAPTCHA-blocked
  # by DuckDuckGo, and the trafilatura path had intermittent
  # ECONNRESETs on github.com. Both omp versions handle those cases.

  # Pi extension: `context7` tool. Wraps the Context7 REST API to fetch
  # up-to-date, version-specific library documentation and code examples.
  #
  # Uses two endpoints:
  #   1. https://context7.com/api/v2/libs/search — search by name + query
  #   2. https://context7.com/api/v2/context     — get docs for a library
  #
  # API key is optional (read from CONTEXT7_API_KEY env var). Works
  # without it at lower rate limits, same as the Claude Code plugin.
  context7Extension = pkgs.writeText "context7.ts" ''
    /**
     * Pi extension: `context7` tool for library documentation lookup.
     *
     * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
     * edit the Nix source and rebuild.
     *
     * Wraps the Context7 REST API (https://context7.com/api/v2).
     * API key is optional — falls back to rate-limited unauthenticated access.
     */
    import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
    import { Type } from "typebox";
    import { StringEnum } from "@earendil-works/pi-ai";

    const BASE_URL = "https://context7.com/api/v2";
    const DEFAULT_TIMEOUT_MS = 30000;

    const apiKey = process.env.CONTEXT7_API_KEY ?? "";
    const authHeader = apiKey ? { "Authorization": "Bearer " + apiKey } : {};

    interface SearchResult {
      id: string;
      title: string;
      description: string;
      branch: string;
      lastUpdateDate: string;
      state: string;
      totalTokens: number;
      totalSnippets: number;
      stars: number;
      trustScore: number;
      benchmarkScore: number;
      versions?: string[];
    }

    interface SearchResponse {
      results: SearchResult[];
      searchFilterApplied: boolean;
    }

    interface CodeSnippet {
      codeTitle: string;
      codeDescription: string;
      codeLanguage: string;
      codeTokens: number;
      codeId: string;
      pageTitle: string;
      codeList: Array<{
        language: string;
        code: string;
      }>;
    }

    interface InfoSnippet {
      pageId: string;
      breadcrumb: string;
      content: string;
      contentTokens: number;
    }

    interface ContextResponse {
      codeSnippets: CodeSnippet[];
      infoSnippets: InfoSnippet[];
    }

    async function context7Fetch<T>(
      path: string,
      signal: AbortSignal | undefined,
    ): Promise<T> {
      const url = BASE_URL + path;
      const res = await fetch(url, {
        headers: { ...authHeader, "Content-Type": "application/json" },
        signal,
      });
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new Error(
          "Context7 API " + res.status + ": " + text.slice(0, 500),
        );
      }
      return res.json();
    }

    function formatSearchResults(res: SearchResponse): string {
      if (!res.results || res.results.length === 0) {
        return "No libraries found matching your query.";
      }
      const lines = res.results.slice(0, 10).map((r, i) => {
        const ver = r.versions && r.versions.length > 0
          ? " (" + r.versions.slice(0, 3).join(", ") + "...)"
          : "";
        return (
          (i + 1) + ". " + r.title + " (" + r.id + ")" + ver + "\n" +
          "   " + r.description + "\n" +
          "   stars: " + r.stars + "  trust: " + r.trustScore +
          "  snippets: " + r.totalSnippets
        );
      });
      return "Found " + res.results.length + " libraries:\n\n" + lines.join("\n\n");
    }

    function formatContextResponse(res: ContextResponse): string {
      const parts: string[] = [];

      if (res.infoSnippets && res.infoSnippets.length > 0) {
        const info = res.infoSnippets.slice(0, 10).map((s) => {
          const content = s.content.length > 2000
            ? s.content.slice(0, 2000) + "... (truncated)"
            : s.content;
          return "---\n" + s.breadcrumb + "\n\n" + content;
        });
        parts.push("## Information\n" + info.join("\n"));
      }

      if (res.codeSnippets && res.codeSnippets.length > 0) {
        const code = res.codeSnippets.map((s) => {
          const codeBlock = s.codeList.map((c) =>
            "```" + c.language + "\n" + c.code + "\n```"
          ).join("\n\n");
          return "## " + s.codeTitle + " (" + s.pageTitle + ")\n" +
            (s.codeDescription ? s.codeDescription + "\n\n" : "") +
            codeBlock +
            "\nSource: " + s.codeId;
        });
        parts.push("## Code Examples\n" + code.join("\n\n"));
      }

      if (parts.length === 0) {
        return "No documentation found for this query.";
      }

      return parts.join("\n\n") + "\n";
    }

    export default function (pi: ExtensionAPI) {
      pi.registerTool({
        name: "context7",
        label: "Context7 Documentation",
        description:
          "Fetch up-to-date, version-specific library documentation and " +
          "code examples from Context7. Solves the problem of AI assistants " +
          "relying on outdated training data by fetching real-time docs from " +
          "the source. Two-step workflow: first search for the library " +
          "(resolve-library-id), then query its documentation (query-docs). " +
          "Use even when you think you know the answer — training data may " +
          "not reflect recent changes.",
        parameters: Type.Object({
          tool: StringEnum(
            ["resolve-library-id", "query-docs"] as const,
            {
              description:
                'Tool to call: "resolve-library-id" (search) or "query-docs" (fetch docs).',
            },
          ),
          libraryName: Type.Optional(Type.String({
            description:
              "Library name to search (e.g. \"Next.js\", \"React\", \"Prisma\"). " +
              "Used with resolve-library-id. If omitted, `query` is used " +
              "as the library name and a relevance-only search runs.",
          })),
          query: Type.String({
            description:
              "Query for relevance ranking. For resolve-library-id: describe " +
              "what you want to do with the library (also doubles as the " +
              "library name when libraryName is omitted). For query-docs: " +
              "your specific question about the library.",
          }),
          libraryId: Type.Optional(Type.String({
            description:
              "Library ID from resolve-library-id results (e.g. " +
              '"/vercel/next.js"). Required for query-docs.',
          })),
          maxResults: Type.Optional(Type.Integer({
            description:
              "Maximum results to return (default 10).",
            minimum: 1,
            maximum: 50,
          })),
        }),
        async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
          const timeoutCtl = new AbortController();
          const timeoutId = setTimeout(
            () => timeoutCtl.abort(),
            DEFAULT_TIMEOUT_MS,
          );
          const combinedSignal = signal
            ? AbortSignal.any([signal, timeoutCtl.signal])
            : timeoutCtl.signal;

          try {
            if (params.tool === "resolve-library-id") {
              // Fall back to `query` as the library name when libraryName
              // is omitted — the most common model-side mistake is to skip
              // libraryName and put everything in query, since omp/Context7
              // documents this as a single search call.
              const libraryName = params.libraryName ?? params.query;
              if (!libraryName) {
                return {
                  content: [{
                    type: "text",
                    text: "Error: provide `libraryName` or `query` to search for. " +
                      "Example: libraryName='React', query='How to use useEffect'.",
                  }],
                  details: { tool: params.tool, error: "missing_library_name" },
                };
              }
              const maxResults = params.maxResults ?? 10;
              const path =
                "/libs/search?libraryName=" +
                encodeURIComponent(libraryName) +
                "&query=" +
                encodeURIComponent(params.query) +
                "&maxResults=" + maxResults;

              let data: SearchResponse;
              try {
                data = await context7Fetch<SearchResponse>(path, combinedSignal);
              } catch (err: unknown) {
                const msg = err instanceof Error ? err.message : String(err);
                if (msg.includes("401") || msg.includes("403")) {
                  return {
                    content: [{
                      type: "text",
                      text: "Context7 API returned 401/403. The API may require " +
                        "a free API key. Set CONTEXT7_API_KEY in your environment " +
                        "(get one at https://context7.com/dashboard, it\'s free). " +
                        "\n\nError: " + msg,
                    }],
                    details: { tool: params.tool, error: "auth_required" },
                  };
                }
                return {
                  content: [{
                    type: "text",
                    text: "Context7 search failed: " + msg,
                  }],
                  details: { tool: params.tool, error: "api_error", message: msg },
                };
              }

              return {
                content: [{ type: "text", text: formatSearchResults(data) }],
                details: {
                  tool: "resolve-library-id",
                  libraryName,
                  query: params.query,
                  count: data.results?.length ?? 0,
                },
              };
            } else if (params.tool === "query-docs") {
              const libraryId = params.libraryId;
              if (!libraryId) {
                return {
                  content: [{
                    type: "text",
                    text: "Error: libraryId is required for query-docs. " +
                      "First use resolve-library-id to find the library, then " +
                      "pass its ID here. Example: libraryId='/vercel/next.js'.",
                  }],
                  details: { tool: params.tool, error: "missing_library_id" },
                };
              }
              const path =
                "/context?libraryId=" +
                encodeURIComponent(libraryId) +
                "&query=" +
                encodeURIComponent(params.query) +
                "&type=json";

              let data: ContextResponse;
              try {
                data = await context7Fetch<ContextResponse>(path, combinedSignal);
              } catch (err: unknown) {
                const msg = err instanceof Error ? err.message : String(err);
                if (msg.includes("401") || msg.includes("403")) {
                  return {
                    content: [{
                      type: "text",
                      text: "Context7 API returned 401/403. The API may require " +
                        "a free API key. Set CONTEXT7_API_KEY in your environment " +
                        "(get one at https://context7.com/dashboard, it\'s free). " +
                        "\n\nError: " + msg,
                    }],
                    details: { tool: params.tool, error: "auth_required" },
                  };
                }
                return {
                  content: [{
                    type: "text",
                    text: "Context7 docs lookup failed: " + msg,
                  }],
                  details: { tool: params.tool, error: "api_error", message: msg },
                };
              }

              return {
                content: [{ type: "text", text: formatContextResponse(data) }],
                details: {
                  tool: "query-docs",
                  libraryId: libraryId,
                  query: params.query,
                  snippets: data.codeSnippets?.length ?? 0,
                  info: data.infoSnippets?.length ?? 0,
                },
              };
            } else {
              return {
                content: [{
                  type: "text",
                  text: "Unknown tool: " + params.tool,
                }],
                details: { tool: params.tool, error: "unknown_tool" },
              };
            }
          } finally {
            clearTimeout(timeoutId);
          }
        },
      });
    }
  '';

  # Pi extension: single `lsp` tool exposing 14 actions across LSP
  # (diagnostics, hover, definition / type_definition / implementation,
  # references, document & workspace symbols, code_actions, rename,
  # rename_file, status, reload, capabilities, raw request). Language
  # server binaries are substituted from Nix store paths at build time.
  lspExtension = pkgs.writeText "lsp.ts" (
    builtins.replaceStrings
      [ "___GOLANG_LSP___" "___TS_LSP___" "___RUST_ANALYZER___" "___NIX_LSP___" ]
      [
        "${pkgs.gopls}/bin/gopls"
        "${pkgs.nodePackages.typescript-language-server}/bin/typescript-language-server"
        "${pkgs.rust-analyzer}/bin/rust-analyzer"
        "${pkgs.nil}/bin/nil"
      ]
      (builtins.readFile ./lsp-extension.ts)
  );

  # Pi extension: `ast_grep` tool. Backed by `pi-rs ast-grep` (in-tree
  # tree-sitter via the pi-ast crate). Replaces the previous wrapper
  # around the standalone `sg` binary; gives meta-variable capture,
  # parse-error collection, and pagination matching omp's surface.
  astGrepExtension = pkgs.writeText "ast-grep.ts" (
    builtins.replaceStrings [ "___PI_RS_BIN___" ] [ "${piRs}/bin/pi-rs" ] (
      builtins.readFile ./ast-grep-extension.ts
    )
  );

  # Pi extension: `ast_edit` tool. Backed by `pi-rs ast-edit`. Previews
  # rewrites by default; writes to disk when called with `apply: true`.
  astEditExtension = pkgs.writeText "ast-edit.ts" (
    builtins.replaceStrings [ "___PI_RS_BIN___" ] [ "${piRs}/bin/pi-rs" ] (
      builtins.readFile ./ast-edit-extension.ts
    )
  );

  # Pi extension: bash-command rewrite hook for pi-rs token compression.
  # Sits on the `tool_call` event; for every Bash tool invocation, calls
  # `pi-rs rewrite` and mutates `event.input.command` if a rule fires.
  # Mirror of the per-agent shims for claude/cursor/codex — same binary
  # contract, single source of truth in rewrite/rules.rs.
  #
  # The template lives in the source tree and is also copied verbatim
  # into the pi-rs derivation's share/ output for the documentation
  # surface — we read directly from the source path here to avoid an
  # import-from-derivation that would force pi-rs to build during eval
  # (which breaks cross-arch `nix flake check`).
  piRsRewriteExtension = pkgs.writeText "pi-rs-rewrite.ts" (
    builtins.replaceStrings [ "___PI_RS_BIN___" ] [ "${piRs}/bin/pi-rs" ] (
      builtins.readFile ../../home/cli/pi-rs/agent-hooks/pi-rewrite-extension.ts
    )
  );

  # Pi extension: `browser_run` tool. Thin wrapper around `dev-browser`
  # (npm-global). Resolves the binary from PATH at spawn time, so this
  # extension assumes `dev-browser` is installed via `npm install -g
  # dev-browser` (and `dev-browser install` was run once to pull Chromium).
  webBrowserRunExtension = pkgs.writeText "browser-run.ts" ''
    /**
     * Pi extension: `browser_run` tool.
     *
     * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
     * edit the Nix source and rebuild.
     */
    import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
    import { Type } from "typebox";
    import { spawn } from "node:child_process";
    import { Buffer } from "node:buffer";

    const DEV_BROWSER = "dev-browser"; // resolved from PATH
    const DEFAULT_PROFILE = "pi";
    const DEFAULT_TIMEOUT_S = 30;
    const MAX_OUTPUT_CHARS = 100000;

    type ConnectArg = boolean | string;

    interface Details {
      browser: string;
      headless: boolean;
      connect: ConnectArg;
      timeout: number;
      argv?: string[];
      exit_code?: number;
      stderr?: string;
      stdout_chars?: number;
      truncated?: boolean;
      elapsed_ms?: number;
      error?: string;
    }

    function runDevBrowser(
      args: string[],
      scriptInput: string,
      signal: AbortSignal | undefined,
    ): Promise<{ stdout: string; stderr: string; code: number }> {
      return new Promise((resolve, reject) => {
        // In default --connect mode dev-browser does not launch Chromium
        // (it attaches via CDP to a Chrome started with
        // --remote-debugging-port=9222), so PLAYWRIGHT_BROWSERS_PATH from
        // home/cli/development.nix does not matter and we pass env as-is.
        const child = spawn(DEV_BROWSER, args, { signal, env: process.env });
        const out: Buffer[] = [];
        const err: Buffer[] = [];
        child.stdout.on("data", (c: Buffer) => out.push(c));
        child.stderr.on("data", (c: Buffer) => err.push(c));
        child.on("error", reject);
        child.on("close", (code) => {
          resolve({
            stdout: Buffer.concat(out).toString("utf8"),
            stderr: Buffer.concat(err).toString("utf8"),
            code: code ?? -1,
          });
        });
        child.stdin.on("error", () => { /* swallow EPIPE */ });
        child.stdin.write(scriptInput);
        child.stdin.end();
      });
    }

    export default function (pi: ExtensionAPI) {
      pi.registerTool({
        name: "browser_run",
        label: "Browser Run",
        description:
          "Execute a JavaScript script in a sandboxed QuickJS runtime with " +
          "a pre-connected Playwright `browser` global. Use for end-to-end " +
          "testing of frontend apps: navigation, form filling, assertions, " +
          "screenshots, snapshotForAI. The script is NOT Node.js — no " +
          "require/import, no fetch, no fs/path/os/process. Available " +
          "globals: browser (Playwright Page API), console, setTimeout, " +
          "saveScreenshot(buf, name), writeFile(name, data), readFile(name). " +
          "By default ATTACHES to a Chrome already running with " +
          "--remote-debugging-port=9222 (auto-discover via CDP). Pass " +
          "connect: false to launch daemon-managed Chromium instead " +
          "(rarely needed; known issues on NixOS). See the dev-browser " +
          "skill for recipes.",
        parameters: Type.Object({
          script: Type.String({
            description:
              "QuickJS script body. Top-level await available. NO Node.js " +
              "globals (require/import/fetch/fs/process). Use " +
              "console.log(JSON.stringify(...)) for structured output.",
          }),
          browser: Type.Optional(Type.String({
            description:
              "Named profile (--browser). Only used when connect=false " +
              "(daemon-managed mode). Default 'pi'.",
          })),
          connect: Type.Optional(Type.Union([
            Type.Boolean(),
            Type.String(),
          ], {
            description:
              "true (default): auto-discover a running Chrome with " +
              "--remote-debugging-port=9222. string: connect to that CDP " +
              "URL (e.g. http://localhost:9222). false: launch " +
              "daemon-managed Chromium instead.",
          })),
          headless: Type.Optional(Type.Boolean({
            description: "Default false (headed — you watch tests run).",
          })),
          timeout: Type.Optional(Type.Integer({
            description: "Max script execution time in seconds (default 30).",
            minimum: 5,
            maximum: 600,
          })),
          ignore_https_errors: Type.Optional(Type.Boolean({
            description:
              "Default false. Useful for local dev with self-signed certs.",
          })),
        }),
        async execute(_toolCallId, params, signal, _onUpdate, _ctx) {
          const browser = params.browser ?? DEFAULT_PROFILE;
          const headless = params.headless ?? false;
          const connect: ConnectArg = params.connect ?? true;
          const timeout = params.timeout ?? DEFAULT_TIMEOUT_S;
          const ignoreHttps = params.ignore_https_errors ?? false;

          const args: string[] = [];
          if (connect === false) {
            args.push("--browser", browser);
          } else if (connect === true) {
            args.push("--connect");
          } else {
            args.push("--connect", connect);
          }
          if (headless) args.push("--headless");
          if (ignoreHttps) args.push("--ignore-https-errors");
          args.push("--timeout", String(timeout));

          const details: Details = {
            browser, headless, connect, timeout, argv: args,
          };

          const start = Date.now();
          let r: { stdout: string; stderr: string; code: number };
          try {
            r = await runDevBrowser(args, params.script, signal);
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            const hint = msg.includes("ENOENT")
              ? " (dev-browser not on PATH — install with `npm install -g dev-browser`)"
              : msg.includes("could not connect") || msg.includes("ECONNREFUSED")
                ? " (no Chrome on :9222 — start one with `chromium --remote-debugging-port=9222` or `brave --remote-debugging-port=9222`)"
                : "";
            return {
              content: [{
                type: "text",
                text: "dev-browser spawn failed: " + msg + hint,
              }],
              details: { ...details, error: msg },
            };
          }

          details.elapsed_ms = Date.now() - start;
          details.exit_code = r.code;
          details.stderr = r.stderr;
          details.stdout_chars = r.stdout.length;

          let outputText = r.stdout;
          if (outputText.length > MAX_OUTPUT_CHARS) {
            outputText = outputText.slice(0, MAX_OUTPUT_CHARS) +
              "\n\n[truncated: " + MAX_OUTPUT_CHARS + " of " +
              r.stdout.length + " chars shown]";
            details.truncated = true;
          }

          const modeDesc = connect === false
            ? "profile=" + browser
            : connect === true
              ? "connect=auto"
              : "connect=" + connect;
          const header =
            "[browser_run " + modeDesc +
            (headless ? " headless" : " headed") +
            "] exit=" + r.code + " elapsed=" + details.elapsed_ms + "ms" +
            (r.stderr.trim()
              ? "\n--- stderr ---\n" + r.stderr.slice(0, 2000)
              : "") +
            "\n--- stdout ---\n";

          return {
            content: [{ type: "text", text: header + outputText }],
            details,
          };
        },
      });
    }
  '';
in
{
  # Pi auto-discovers single-file extensions in this directory.
  # See: ~/.npm-global/lib/node_modules/@earendil-works/pi-coding-agent/README.md
  # (Customization → Extensions).
  # Install pi-rs into the user environment so the TS extensions can
  # spawn `pi-rs <subcommand>` without baking a per-host store path. Same
  # binary, three triples (x86_64-linux, aarch64-linux, aarch64-darwin).
  home.packages = [ piRs ];

  # Pi has no built-in vim mode; @burneikis/pi-vim replaces the composer
  # with a vim-modal editor. Seed the package into settings.json so pi
  # auto-loads it on startup.
  home.activation.piVimMode = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    target="${config.home.homeDirectory}/.pi/agent/settings.json"
    mkdir -p "$(dirname "$target")"
    pkg="npm:@burneikis/pi-vim"
    if [[ -f "$target" ]]; then
      existing="$(cat "$target")"
    else
      existing='{}'
    fi
    printf '%s' "$existing" \
      | ${pkgs.jq}/bin/jq --arg pkg "$pkg" '
          .packages = ((.packages // []) + [$pkg] | unique)
        ' \
      > "$target.tmp"
    mv "$target.tmp" "$target"
    chmod 0600 "$target"
  '';

  home.file.".pi/agent/extensions/context7.ts".source = context7Extension;
  home.file.".pi/agent/extensions/lsp.ts".source = lspExtension;
  home.file.".pi/agent/extensions/ast-grep.ts".source = astGrepExtension;
  home.file.".pi/agent/extensions/ast-edit.ts".source = astEditExtension;
  home.file.".pi/agent/extensions/browser-run.ts".source = webBrowserRunExtension;
  home.file.".pi/agent/extensions/pi-rs-rewrite.ts".source = piRsRewriteExtension;

  # pi-rs-backed primitives. These are thin TS shells that spawn the
  # `pi-rs <subcommand>` binary installed via `home.packages` above.
  home.file.".pi/agent/extensions/code-search.ts".source = ./pi-extensions/code-search.ts;
  home.file.".pi/agent/extensions/code-summary.ts".source = ./pi-extensions/code-summary.ts;
  home.file.".pi/agent/extensions/code-hash.ts".source = ./pi-extensions/code-hash.ts;

  # Directory-style `web_fetch` and `web_search` extensions, both forked
  # from oh-my-pi. They register the canonical tool names; the older
  # single-file ddgr+trafilatura versions were retired in favor of these.
  home.file.".pi/agent/extensions/web-fetch".source = webFetchOmpExtension;
  home.file.".pi/agent/extensions/web-search".source = webSearchOmpExtension;

  # Master cycle list for Ctrl+P / Shift+Ctrl+P. Seeded into
  # ~/.pi/agent/settings.json -> enabledModels by
  # home/services/pi-models.nix on the first activation that finds
  # the field unset. After that, pi's /scoped-models interactive UI
  # owns the field — including any per-model thinking-level overrides
  # (xhigh for Opus, off for the local Qwen, etc.).
  #
  # Provider/id qualification is mandatory here: `claude-opus-4-7`
  # exists both as a built-in Anthropic model AND as a route on the
  # corporate LiteLLM gateway, so we have to be explicit about which
  # path each cycle slot takes. Anthropic models go direct via
  # ANTHROPIC_API_KEY (fish-exported from /run/secrets); the four GPT
  # and Gemini entries route through litellm. The qwen3.6-* glob
  # tolerates the per-host quant suffix (Q4 on workstation, Q8 on VM
  # hosts that talk to mac-work).
  services.piModels.enabledModels = [
    "anthropic/claude-opus-4-7"
    "litellm/gpt-5.5"
    "litellm/gpt-5.4"
    "litellm/gemini-2.5-pro"
    "litellm/gemini-2.5-flash"
    "llama-cpp/qwen3.6-35b-a3b-*"
  ];

  # Global pi context file. Loaded into every pi session's system prompt.
  # See: pi-coding-agent/README.md (Context Files).
  home.file.".pi/agent/AGENTS.md".text = ''
    Never estimate time, hours, effort, or duration. If asked, refuse and
    offer concrete scope instead (files touched, comparable prior work,
    decision points, unknowns).
  '';

  # Pi skill: chaos / exploratory testing of frontend apps via `browser_run`.
  # Globally available; project-agnostic. Mirrors the in-tree
  # .claude/skills/explore-frontend/SKILL.md from infinity-core but stripped
  # of project-specific conventions (bug templates, BOARD.md, k8s/compose
  # mode resolution, service-name URL lookup).
  home.file.".pi/agent/skills/explore-frontend/SKILL.md".text = ''
    ---
    name: explore-frontend
    description: |
      Chaos / exploratory testing of a frontend app via the `browser_run`
      tool. Act as a destructive user: exercise every reachable path,
      poke forms with adversarial inputs, surface every bug the UI can
      reveal. Trigger phrases: "explore the UI", "explore the frontend",
      "chaos test", "break the UI", "bug hunt the UI", "QA the UI",
      "test the frontend", "smoke test the UI", "act as a user",
      "post-deploy UX verification". Requires Chrome running with
      --remote-debugging-port=9222; ask the user to start one if not
      already running. Accepts a URL; ask if not provided.
    ---

    # Explore Frontend

    You are a **chaos explorer**. Curious, relentless, destructive. You do
    not use the app politely — you poke every corner, fill forms with
    garbage, click things twice, navigate backwards, resize, interrupt
    loads, and test what happens when things go wrong. Your goal is to
    find every way the app can break and surface each failure.

    ## Prerequisites

    `browser_run` defaults to attaching via CDP on `localhost:9222`. If
    Chrome is not running with debug enabled, tell the user to start it:

    ```
    google-chrome --remote-debugging-port=9222
    # or
    chromium --remote-debugging-port=9222
    # or
    brave --remote-debugging-port=9222
    ```

    Do not try `connect: false` (daemon-managed Chromium) — known issues
    on NixOS (chromium version mismatch + missing shared libs).

    ## Resolving the target

    The user provides a URL. If they only give a service name or "the
    app", ask which URL they want tested. Do not guess.

    ## Phase 1: Reconnaissance

    ### 1.1 Launch and snapshot

    Call `browser_run` with:

    ```js
    const page = await browser.getPage("explore");
    await page.goto("TARGET_URL", { waitUntil: "domcontentloaded" });
    const snap = await page.snapshotForAI();
    console.log(JSON.stringify({
      url: page.url(),
      title: await page.title(),
      snapshot: snap.full,
    }, null, 2));
    ```

    ### 1.2 Build the map

    From the initial snapshot, identify:
    - All visible links and navigation elements
    - All forms and input fields
    - All buttons and interactive elements
    - Overall page structure (sidebar, header, main content, modals)

    Log the map as a checklist — you will work through it systematically.

    ### 1.3 Baseline console errors

    Before exploring, capture pre-existing state so you can distinguish
    new errors from ones already there:

    ```js
    const page = await browser.getPage("explore");
    const errors = [];
    page.on("pageerror", (e) => errors.push({ type: "pageerror", message: e.message }));
    page.on("console", (msg) => {
      if (msg.type() === "error") errors.push({ type: "console-error", text: msg.text() });
    });
    await page.waitForTimeout(2000);
    console.log(JSON.stringify({ baseline_errors: errors }, null, 2));
    ```

    ## Phase 2: Systematic exploration

    Work through every reachable path. For each page or view:

    ### 2.1 Navigate and snapshot

    ```js
    const page = await browser.getPage("explore");
    await page.goto("URL", { waitUntil: "domcontentloaded" });
    await page.waitForLoadState("networkidle");
    const snap = await page.snapshotForAI();
    console.log(JSON.stringify({
      url: page.url(),
      title: await page.title(),
      snapshot: snap.full,
    }, null, 2));
    ```

    ### 2.2 Exercise every interactive element

    For each element on the page, try the appropriate chaos.

    **Links & navigation**
    - Click every link, verify it loads, check for 404s / error pages
    - Use browser back/forward after each navigation
    - Try the same link twice rapidly

    **Forms & inputs**
    - Submit empty forms — does validation work?
    - Fill text fields with: empty string, single space, 5000 characters,
      `<script>alert(1)</script>`, `'; DROP TABLE users;--`, unicode
      (`\u0000`, emoji, RTL text), negative numbers, `NaN`, `Infinity`
    - Number fields: text, negative values, zero, `MAX_SAFE_INTEGER`
    - Date fields: invalid dates, far-future dates, epoch zero
    - File uploads: skip the file, try wrong format
    - Submit the same form twice rapidly (double-submit)
    - Fill a form, navigate away, come back — is state preserved or properly cleared?

    **Buttons & actions**
    - Click every button and observe the result
    - Click action buttons twice quickly (double-click / double-submit)
    - Click delete/destructive buttons — is there a confirmation?
    - Try actions in unexpected order (e.g., delete before save)

    **State & edge cases**
    - Refresh the page mid-action
    - Navigate directly to deep URLs (skip the normal flow)
    - Test with empty data states (no items in a list)
    - Test loading states — interrupt with navigation

    ### 2.3 Interaction template

    For each interaction, run a focused script that captures console
    errors, takes a screenshot, and reports the resulting state:

    ```js
    const page = await browser.getPage("explore");
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    page.on("console", (msg) => {
      if (msg.type() === "error") errors.push(msg.text());
    });

    // === your interaction ===
    // await page.fill("input[name=email]", "<script>alert(1)</script>");
    // await page.click("button[type=submit]");
    // await page.waitForTimeout(1000);

    const shot = await saveScreenshot(
      await page.screenshot(),
      "after-" + Date.now() + ".png",
    );
    console.log(JSON.stringify({
      url: page.url(),
      title: await page.title(),
      errors,
      screenshot: shot,
    }, null, 2));
    ```

    ### 2.4 What counts as a finding

    Flag a finding when you observe ANY of:
    - **Crash**: unhandled exception, white screen, React error boundary
    - **Console error**: new JS error not in the baseline
    - **Broken UI**: elements overlapping, text overflow, missing content, layout shift
    - **Missing validation**: form accepts clearly invalid input
    - **XSS**: injected HTML/script rendered unsanitized
    - **Lost data**: user input disappears on navigation or refresh
    - **Dead interaction**: button/link does nothing (no feedback, no error)
    - **Broken navigation**: page loads wrong content, 404, infinite redirect
    - **Missing error handling**: action fails silently with no user feedback
    - **Race condition**: double-submit creates duplicates / corrupts state
    - **Accessibility**: interactive element not reachable, missing labels (only if obvious)

    ### 2.5 What is NOT a finding

    Do not flag:
    - Intentional behavior you simply dislike
    - Performance that seems slow but is within reason
    - Features that don't exist yet
    - Styling preferences

    ## Phase 3: Document findings

    For each confirmed finding, capture evidence and record it.

    ### 3.1 Screenshot

    Already done inline in 2.3. Note the path returned by `saveScreenshot`.

    ### 3.2 Record the finding

    Without project-specific context, write findings to
    `EXPLORATION-FINDINGS.md` in the current working directory. If the
    user has a project convention (a `bugs/` directory, a bug template, an
    issue tracker), ask where findings should go before filing — don't
    invent infrastructure they don't have.

    Each finding gets a numbered entry:

    ```markdown
    ## Finding N: <short title>

    - **Severity:** critical | high | medium | low
    - **URL:** http://localhost:...
    - **Steps to reproduce:**
      1. ...
      2. ...
    - **Expected:** ...
    - **Actual:** ...
    - **Console errors:** ...
    - **Screenshot:** path/from/saveScreenshot
    - **Suggested fix (if obvious):** ...
    ```

    ### 3.3 Severity guide

    - **critical**: app crashes, data loss, security vuln (XSS, injection,
      auth bypass), PCI/PII leak
    - **high**: feature completely broken, error state with no recovery,
      5xx on a core path, unauthenticated access to a guarded route
    - **medium**: partial functionality loss, missing validation,
      confusing UX on error, 4xx where success was expected, a11y
      keyboard-trap
    - **low**: minor visual glitch, cosmetic issue under edge-case input,
      non-blocking warning

    ## Phase 4: Depth exploration

    After the first pass, go deeper.

    ### 4.1 Multi-page flows
    - Start a multi-step flow (wizard, checkout) and abandon halfway
    - Complete a flow, then try to redo it
    - Open the same flow in two tabs (use `browser.newPage()`)

    ### 4.2 State boundaries
    - Fill a page with maximum data, then try to add one more
    - Delete all items, then try actions that assume items exist
    - Try actions as if unauthenticated (clear cookies if applicable)

    ### 4.3 Network disruption

    Test what happens when API calls fail:

    ```js
    const page = await browser.getPage("explore");
    await page.route("**/api/**", (route) => route.abort());
    await page.click("button.save");
    await page.waitForTimeout(2000);
    const shot = await saveScreenshot(
      await page.screenshot(),
      "no-api.png",
    );
    const snap = await page.snapshotForAI();
    console.log(JSON.stringify({
      url: page.url(),
      snapshot: snap.full,
      screenshot: shot,
    }, null, 2));
    await page.unroute("**/api/**");
    ```

    ## Phase 5: Report

    After exhausting paths, compile a summary:

    ```markdown
    ## Exploration Report

    **Target**: <URL>
    **Pages explored**: <count>
    **Interactions tested**: <count>
    **Findings**: <count>

    ### Findings summary
    | # | Severity | Title | URL |
    |---|----------|-------|-----|
    | 1 | critical | ... | ... |
    | 2 | high     | ... | ... |

    ### Coverage
    - [x] All navigation links
    - [x] All forms (happy + chaos inputs)
    - [x] Double-submit / rapid clicks
    - [x] Empty states
    - [x] Error states (network failure)
    - [x] Back/forward navigation
    - [x] Direct URL access
    - [ ] <anything you couldn't reach and why>

    ### Areas that held up well
    <what worked correctly despite abuse>
    ```

    ## Rules

    - **One script per action.** Keep `browser_run` calls small and
      focused. One navigation, one interaction, one check per script.
      Read the output before deciding the next action.
    - **Always snapshot after interaction.** Use `page.snapshotForAI()`
      or screenshots to see the result of every action.
    - **Record findings immediately.** Don't batch them up — log each one
      the moment you confirm it.
    - **Named pages persist.** Use `browser.getPage("explore")`
      consistently so you don't lose your place. Create additional named
      pages (e.g., `"explore-tab2"`) only for multi-tab tests.
    - **Be destructive, not random.** Every chaos action should test a
      real failure mode. Random clicking is not useful — targeted abuse
      is.
    - **Stop when stuck.** If a page requires authentication or data you
      don't have, note it in the report and move on.
  '';

  # Pi skill: on-demand instructions for using the `browser_run` tool to
  # E2E-test frontend apps via dev-browser. Auto-loaded when the
  # conversation calls for browser testing / frontend automation.
  # See: pi-coding-agent/docs/skills.md.
  home.file.".pi/agent/skills/dev-browser/SKILL.md".text = ''
    ---
    name: dev-browser
    description: |
      Use this skill when the user asks to test, debug, or automate a
      frontend app in a real browser — especially E2E flows on localhost
      dev servers. Invoke the `browser_run` tool with a QuickJS script.
    ---

    # dev-browser

    Sandboxed Playwright-backed browser automation for E2E testing.
    Invoke via the `browser_run` tool.

    ## When to use

    - End-to-end testing of frontend apps running on localhost
    - Asserting page state (text, element presence, URL after navigation)
    - Filling forms, clicking buttons, verifying outcomes
    - Taking screenshots when something looks wrong
    - Inspecting current state of a running browser tab

    ## Sandbox rules — NOT Node.js

    Scripts execute in a QuickJS WASM sandbox:

    - No `require()`, `import()`, dynamic import
    - No `fetch`, `WebSocket`
    - No `fs`, `path`, `os`, `process`, `__dirname`, `__filename`

    Available globals inside scripts:

    - `browser` — preconnected Playwright handle
    - `console.log/info/warn/error`
    - `setTimeout`, `clearTimeout`
    - `await saveScreenshot(buffer, name)` — writes to ~/.dev-browser/tmp/, returns path
    - `await writeFile(name, data)` — writes to ~/.dev-browser/tmp/
    - `await readFile(name)` — reads from ~/.dev-browser/tmp/

    ## Conventions

    - **Single shared profile.** Always use the default `pi` profile.
      Do not pass a different `browser` name unless the user explicitly
      asks for isolation. The user wants fewer profiles, not more.
    - **Headed by default.** Leave `headless` off so the user watches.
    - **Localhost first.** Default assumption is testing localhost dev
      servers; ask the user for the URL/port if not provided.
    - **Screenshot on assertion failure.** When an assertion fails,
      capture a screenshot via `saveScreenshot` and include the path in
      output. Don't snapshot on every step — only on failures or when
      explicitly asked.
    - **One script, sequenced.** Prefer a single `browser_run` call
      with sequenced actions over multiple tool calls. Playwright's
      auto-waiting works best within one script.
    - **Structured output.** Use `console.log(JSON.stringify({...}))`
      so results are easy to parse.

    ## Common API

    ```js
    const page = await browser.getPage("main");    // get/create named page
    await page.goto(url, { waitUntil: "domcontentloaded" });
    await page.title();
    page.url();
    await page.snapshotForAI();                     // AI-optimized DOM snapshot
    await page.getByRole("button", { name: "Login" }).click();
    await page.fill(selector, value);
    await page.click(selector);
    await page.type(selector, text);
    await page.press(selector, "Enter");
    await page.waitForSelector(selector);
    await page.waitForURL(urlPattern);
    await page.waitForLoadState("networkidle");
    await page.textContent(selector);
    await page.innerHTML(selector);
    await page.$eval(selector, fn);
    await page.$$eval(selector, fn);
    await page.evaluate(fn);                         // run JS in page context
    await page.screenshot();                         // returns Buffer
    await browser.listPages();                       // [{id, url, title, name}]
    await browser.newPage();                         // anonymous, cleaned up
    await browser.closePage("main");                 // discard a named page
    ```

    ## Recipes

    ### Navigate and assert title

    ```js
    const page = await browser.getPage("main");
    await page.goto("http://localhost:3000", { waitUntil: "domcontentloaded" });
    const title = await page.title();
    console.log(JSON.stringify({ url: page.url(), title }));
    ```

    ### Inspect current page state (AI snapshot)

    ```js
    const page = await browser.getPage("main");
    const snap = await page.snapshotForAI();
    console.log(snap.full);
    ```

    ### Login flow with success assertion

    ```js
    const page = await browser.getPage("main");
    await page.goto("http://localhost:3000/login");
    await page.fill("input[name=email]", "alice@example.com");
    await page.fill("input[name=password]", "secret");
    await page.click("button[type=submit]");
    await page.waitForURL(/\/dashboard/);
    const heading = await page.textContent("h1");
    const passed = heading?.includes("Welcome");
    if (!passed) {
      const shot = await saveScreenshot(
        await page.screenshot(),
        "login-fail-" + Date.now() + ".png",
      );
      console.error(JSON.stringify({
        error: "unexpected heading after login",
        heading, url: page.url(), screenshot: shot,
      }));
    } else {
      console.log(JSON.stringify({ passed: true, heading }));
    }
    ```

    ### Capture console errors from the page

    ```js
    const page = await browser.getPage("main");
    const errors = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") errors.push(msg.text());
    });
    page.on("pageerror", (err) => errors.push(String(err)));
    await page.goto("http://localhost:3000");
    await page.waitForLoadState("networkidle");
    console.log(JSON.stringify({ errors }));
    ```

    ### List currently open tabs

    ```js
    const tabs = await browser.listPages();
    console.log(JSON.stringify(tabs, null, 2));
    ```

    ### Reset a stuck page

    ```js
    await browser.closePage("main");
    const page = await browser.getPage("main");
    await page.goto("http://localhost:3000");
    ```

    ## Failure modes & fixes

    - **`dev-browser not on PATH`** — user needs to run
      `npm install -g dev-browser` (then `dev-browser install` once to
      pull Chromium).
    - **Script timeout** — bump `timeout` parameter on browser_run.
    - **Element not found** — prefer Playwright locators which
      auto-wait, or call `page.waitForSelector` explicitly first.
    - **Stale page state across runs** — close and recreate the named
      page (see "Reset a stuck page").
    - **Anti-bot / JS-rendered third-party site** — dev-browser handles
      JS, but this skill is for testing the user's own apps. For
      reading public web content prefer the `web_fetch` tool.
  '';
}
