[user]
name = "aragao"
fullName = "Andre Aragao"

[machines.workstation]
hostName = "workstation"
platform = "x86_64-linux"
profile = "workstation"
stateVersion = "25.05"
bluetooth = true
lockScreen = true
autoLogin = false

[machines.hp-laptop]
hostName = "hp-laptop"
platform = "x86_64-linux" 
profile = "laptop"
stateVersion = "25.05"
wirelessInterface = "wlp2s0"
bluetooth = true
lockScreen = true
autoLogin = false

[machines.parallels-vm]
hostName = "parallels-vm"
platform = "aarch64-linux"
profile = "vm"
stateVersion = "25.05"
bluetooth = false
lockScreen = false
autoLogin = false 

[machines.prl-dev-vm]
hostName = "prl-dev-vm"
platform = "aarch64-linux"
profile = "vm"
stateVersion = "25.05"
bluetooth = false
lockScreen = false
autoLogin = false 
