# HP Laptop Hardware Configuration  
# This will be generated by nixos-generate-config when setting up the laptop
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Hardware configuration from actual HP laptop
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Actual filesystem configuration from HP laptop
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/db8305bf-3643-4c31-9d63-df347361f2df";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3010-B95B";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/91e1997b-0b89-4ac8-b6e4-5d01b96bf783"; }
  ];

  # Laptop-specific optimizations
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Enable integrated graphics
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Power management for laptop
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}