# AMD 9950 Workstation Hardware Configuration
# Generated by nixos-generate-config and imported from existing nix-config
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./amd-gpu.nix
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "thunderbolt"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [
      "kvm-amd"
      "k10temp"
      "nct6775" # ASRock X870E Taichi Super I/O sensors for board fan RPMs
      "mt7925e"
      "msr" # MSR access for CPU power management
    ];
    extraModulePackages = [ ];
    # Use the modern AMD P-State driver in active mode (EPP-based) for the 9950X
    # instead of acpi-cpufreq — gives finer-grained boost behavior on Zen 5.
    kernelParams = [ "amd_pstate=active" ];

    # 186 GiB of RAM — strongly prefer dropping page cache over swapping anon pages.
    kernel.sysctl."vm.swappiness" = 10;
  };
  environment.systemPackages = with pkgs; [
    nvme-cli
    powertop
    smartmontools
    s-tui
    stress-ng
    lm_sensors # sensors, pwmconfig for fan control
  ];

  fileSystems = {
    # Root filesystem on btrfs with @ subvolume
    "/" = {
      device = "/dev/disk/by-uuid/f557ae50-374c-4c65-934a-d71356d119db";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd:1"
        "noatime"
      ];
    };

    # Boot partition
    "/boot" = {
      device = "/dev/disk/by-uuid/79B2-0CFC";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    # Nix store on btrfs subvolume @nix (compressed)
    "/nix" = {
      device = "/dev/disk/by-uuid/f557ae50-374c-4c65-934a-d71356d119db";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "compress=zstd:1"
        "noatime"
      ];
    };
  };

  # Monthly scrub of the btrfs pool catches silent bitrot on the
  # T700 NVMe before it propagates into store paths. Both / and /nix
  # are subvolumes of the same FS, so a single scrub covers everything.
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  # Swap device
  swapDevices = [
    { device = "/dev/disk/by-uuid/5bc24bc4-4f67-4c21-8d4d-e15a9eeef8f7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp108s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp108s0f1.useDHCP = lib.mkDefault true;

  hardware = {
    enableRedistributableFirmware = true;
    # AMD-specific optimizations
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  # Power management — use power-saver governor for lower temps.
  # Dropped from "performance" after testing showed a 21°C reduction
  # with higher throughput (lower-frequency CPUs are more energy-efficient).
  # See: https://skatterbencher.com/2024/09/06/undervolt-ryzen-9000/
  powerManagement.cpuFreqGovernor = "powersave";

  # Power Profiles Daemon — power-saver mode for sustained low temps.
  services.power-profiles-daemon.enable = true;

  # Ensure power-saver profile is set on every boot.
  systemd.services.power-profiles-saver = {
    description = "Set power-profiles-daemon to power-saver mode";
    wantedBy = [ "multi-user.target" ];
    after = [ "power-profiles-daemon.service" ];
    serviceConfig.Type = "oneshot";
    serviceConfig.RemainAfterExit = true;
    script = ''
      ${pkgs.power-profiles-daemon}/bin/powerprofilesctl set power-saver
    '';
  };

  # Thermald for proactive thermal management.
  # Zen 5 (Family 26h) is not in thermald's CPU whitelist — force it to run.
  services.thermald.enable = true;
  services.thermald.ignoreCpuidCheck = true;

  # Fan control via lm_sensors for nct6775 Super I/O.
  # CPU fan (pwm1) auto curve: 40C=50%, 50C=60%, 65C=80%, 80C=100%
  # Case fan (pwm2) auto curve: 35C=50%, 50C=70%, 65C=90%, 75C=100%
  hardware.fancontrol = {
    enable = true;
    config = ''
      INTERVAL=10
      DEVPATH=hwmon6=devices/platform/nct6775.656
      DEVNAME=hwmon6=nct6799
      FCTEMPS=hwmon6/device/pwm1=hwmon6/device/temp1_input hwmon6/device/pwm2=hwmon6/device/temp2_input
      FCFANS=hwmon6/device/pwm1=hwmon6/device/fan1_input hwmon6/device/pwm2=hwmon6/device/fan2_input
      MINTEMP=hwmon6/device/pwm1=40 hwmon6/device/pwm2=35
      MAXTEMP=hwmon6/device/pwm1=80 hwmon6/device/pwm2=75
      MINSTART=hwmon6/device/pwm1=150 hwmon6/device/pwm2=150
      MINSTOP=hwmon6/device/pwm1=0 hwmon6/device/pwm2=0
    '';
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
