# AMD 9950 Workstation Hardware Configuration
# Generated by nixos-generate-config and imported from existing nix-config
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "mt7925e" "it87" "r8126" ];
  boot.extraModulePackages = [ ];
  hardware.enableRedistributableFirmware = true;

  # Root filesystem on btrfs with @ subvolume
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f557ae50-374c-4c65-934a-d71356d119db";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  # Boot partition
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/79B2-0CFC";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Nix store on separate ext4 partition
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/ba653b05-b075-4a98-86f7-cd6a50f0d0fb";
    fsType = "ext4";
  };

  # Swap device
  swapDevices = [
    { device = "/dev/disk/by-uuid/5bc24bc4-4f67-4c21-8d4d-e15a9eeef8f7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp108s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp108s0f1.useDHCP = lib.mkDefault true;

  # AMD-specific optimizations
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Enable AMD GPU support
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}