# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ehci_pci"
        "xhci_pci"
        "usbhid"
        "sr_mod"
        "virtio_balloon"
        "virtio_mmio"
        "virtio_net"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
    kernelParams = [
      "xhci_hcd.quirks=0x40"
      "devices.pci_balloon=0"
    ];

    # Bootloader configuration
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    # Enable btrfs support
    supportedFilesystems = [ "btrfs" ];
  };

  # Filesystem configuration
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@root"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };

    "/home/aragao" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@home-aragao"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };

    "/nix" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };

    "/tmp" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@tmp"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };

    "/.snapshots" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@snapshots"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/nixos-boot";
      fsType = "vfat";
    };

    "/swap" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [
        "subvol=@swap"
        "compress=zstd:1"
        "noatime"
        "space_cache=v2"
        "discard=async"
      ];
    };
  };

  # Swap configuration (using btrfs subvolume)
  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 16384; # 16GB swap file
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s5.useDHCP = lib.mkDefault true;

  nixpkgs = {
    hostPlatform = lib.mkDefault "aarch64-linux";
    config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [ "prl-tools" ];
  };
  hardware.parallels = {
    enable = true;
    package = pkgs.prl-tools;
  };

  # Disable the Parallels Shared Printing bridge. This VM never prints,
  # but the service was eating ~100% of one core averaged across its
  # entire uptime (4h 28min process time vs 4h 28min wall-clock) by
  # forking `lpstat -v | sed ...` in a tight loop to enumerate host
  # printers. nixpkgs' hardware.parallels module installs it
  # unconditionally with no opt-out, so we mask the unit directly.
  # `BindsTo=cups.service` in the upstream unit means it would also
  # auto-restart whenever CUPS bounces, which made this hard to spot.
  systemd.services.prlshprint.enable = false;
}
