/**
 * Pi extension: bash-command rewrite hook for pi-rs token compression.
 *
 * Generated by home/cli/pi.nix. Do not edit the deployed file directly;
 * edit home/cli/pi-rs/agent-hooks/pi-rewrite-extension.ts and rebuild.
 *
 * Mirrors what `pi-rs hook claude` and `pi-rs hook cursor` do for those
 * agents, but inside pi's native `tool_call` event loop. Bash commands
 * dispatched by the LLM are intercepted, sent through `pi-rs rewrite`,
 * and mutated in-place if a rule fires. Failures are silently ignored so
 * the hook never breaks a session.
 *
 * Why exec_file the binary instead of importing the rewrite logic
 * directly: keeps the protocol contract uniform across all four agents
 * (claude/cursor/codex/pi). When the rules table grows, every agent
 * picks up the change with no extension-side edits.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { isToolCallEventType } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileP = promisify(execFile);

// Absolute /nix/store path, pinned at home-manager build time.
const PI_RS = "___PI_RS_BIN___";

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    if (!isToolCallEventType("bash", event)) return;
    const original = event.input.command;
    if (!original || typeof original !== "string") return;

    try {
      const { stdout } = await execFileP(PI_RS, ["rewrite", "--", original], {
        // 1s is overkill — `pi-rs rewrite` is a static table lookup.
        timeout: 1000,
      });
      const rewritten = stdout.replace(/\n+$/, "");
      if (rewritten && rewritten !== original) {
        event.input.command = rewritten;
      }
    } catch {
      // Any failure (timeout, ENOENT, non-zero exit) — leave the command
      // unchanged. Hooks must never break the agent.
    }
  });
}
